In [3]:
import numpy as np

In [4]:
cycle_results = [
    {
        'image_timestamp': '20240906-161224.151923',
        'boxes': np.array([[1918,  745, 2237, 1064], [1644, 1603, 2145, 2104]]),
        'centers': [np.array([2077.8040008 ,  904.29510521]), np.array([1894.45985106, 1854.11929306])],
        'exposure_time': 142000
    },
    {
        'image_timestamp': '20240906-161224.151925',
        'boxes': np.array([[1918,  745, 2237, 1064]]),
        'centers': [np.array([2077.8040008 ,  904.29510521])],
        'exposure_time': 142000
    },
    {
        'image_timestamp': '20240906-161224.151929',
        'boxes': np.array([[1644, 1603, 2145, 2104]]),
        'centers': [np.array([1894.45985106, 1854.11929306])],
        'exposure_time': 144000
    },
    {
        'image_timestamp': '20240906-161224.151930',
        'boxes': np.array([[1644, 1603, 2145, 2104]]),
        'centers': [None],
        'exposure_time': 144000
    },
    {
        'image_timestamp': '20240906-161224.151925',
        'boxes': np.array([[1918,  745, 2237, 1064]]),
        'centers': [np.array([2077.8040008 ,  904.29510521]), None],
        'exposure_time': 142000
    },
]

In [15]:
for result in cycle_results:
    for center in result['centers']:
        if center is None:
            print("None")

None
None


In [ ]:
[result['centers'] for result in cycle_results]

In [5]:
cycle_centers = np.concatenate([result['centers'] for result in cycle_results])
cycle_centers

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [25]:
new_cycle_centers = cycle_centers + np.random.normal(0.1, 0.02, size=cycle_centers.shape)
new_cycle_centers

array([[2077.8665956 ,  904.38228788],
       [1894.59515211, 1854.18258924],
       [2077.89902167,  904.3665424 ],
       [1894.57014763, 1854.16873541]])

In [26]:
move_distance = abs(new_cycle_centers - cycle_centers)
move_distance

array([[0.0625948 , 0.08718267],
       [0.13530105, 0.06329618],
       [0.09502087, 0.07143719],
       [0.11029657, 0.04944235]])

In [27]:
over_threshold = move_distance > 0.1
over_threshold

array([[False, False],
       [ True, False],
       [False, False],
       [ True, False]])

In [28]:
over_threshold = np.bitwise_or(over_threshold[:, 0], over_threshold[:, 1])
over_threshold

array([False,  True, False,  True])

In [29]:
over_threshold_index = np.where(over_threshold)[0]
over_threshold_index

array([1, 3])