In [1]:
import numpy as np

In [16]:
directions = {1:-1, 2:1, 3:0, 4:0, 5:-1, 6:1, 7:0, 8:0}
directions

{1: -1, 2: 1, 3: 0, 4: 0, 5: -1, 6: 1, 7: 0, 8: 0}

In [31]:
directions_keys = np.array(list(directions.keys()))
directions_keys

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
directions_values = np.array(list(directions.values()))
directions_values

array([-1,  1,  0,  0, -1,  1,  0,  0])

In [35]:
directions_low_index = np.where(directions_values==-1)[0]
directions_low_index


array([0, 4])

In [36]:
directions_low_keys =directions_keys[directions_low_index]
directions_low_keys

array([1, 5])

In [32]:
directions_ok_index = np.where(directions_values==0)[0]
directions_ok_index

array([2, 3, 6, 7])

In [37]:
directions_ok_keys = directions_keys[directions_ok_index]
directions_ok_keys

array([3, 4, 7, 8])

In [33]:
directions_high_index = np.where(directions_values==1)[0]
directions_high_index

array([1, 5])

In [38]:
directions_high_keys = directions_keys[directions_high_index]
directions_high_keys

array([2, 6])