In [1]:
import numpy as np

## 数组的索引、切片

In [2]:
arr = np.array(
            [[80, 89, 86, 67, 79],
            [78, 97, 89, 67, 81],
            [90, 94, 78, 67, 74],
            [91, 91, 90, 67, 69],
            [76, 87, 75, 67, 86],
            [70, 79, 84, 67, 84],
            [94, 92, 93, 67, 64],
            [86, 85, 83, 67, 80]])
arr

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [3]:
# 先行后列
arr[1][0]

78

In [4]:
arr[1:2, :1]

array([[78]])

### 二维数组索引

In [5]:
stock_change = np.random.normal(0, 1, (4, 5))
# 获取第一个股票的前3个交易日的涨跌幅数据
# 二维的数组，两个维度
stock_change[0, 0:3]

array([0.65380215, 2.2181168 , 0.16889885])

### 三维数组索引

In [7]:
# 三维
a1 = np.array([[[1, 2, 3], [4, 5, 6]], [[12, 3, 34], [5, 6, 7]]])
# 返回结果
# array([[[ 1,  2,  3],
#         [ 4,  5,  6]],
#         [[12,  3, 34],
#         [ 5,  6,  7]]])

a1[0, 0, 0:2]   # 输出: array([1, 2])

array([1, 2])

## bool 索引

In [12]:
a2 = np.linspace(1, 10, 10)
a2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
a2[a2>5]

array([ 6.,  7.,  8.,  9., 10.])

In [14]:
a2[a2>5] = 5
a2

array([1., 2., 3., 4., 5., 5., 5., 5., 5., 5.])