In [1]:
import numpy as np

In [2]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# flip 倒序数据


In [15]:
# 倒序0维度
np.flip(x, axis=0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [16]:
# 倒序0维度
np.flip(x, axis=[0])

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [17]:
# 倒序1维度
np.flip(x, axis=1)

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [18]:
# 倒序1维度
np.flip(x, axis=[1])

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [19]:
# 倒序0,1维度
np.flip(x, axis=[0, 1])

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [20]:
# 默认情况倒序全部维度
np.flip(x)

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])