In [10]:
import matplotlib.pyplot as plt
import numpy as np
import torch
np.random.seed(0)

## 形状修改

In [2]:
stock_change = np.random.normal(0, 1, (4, 5))

###  array.reshape(shape, order) 不改变实际数据
- 将数组变为一行,然后按照列数重新切断,分成不同行
- 返回一个具有相同数据域，但shape不一样的视图
- 行、列不进行互换

In [3]:
stock_change

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [4]:
# 在转换形状的时候，一定要注意数组的元素匹配
stock_change.reshape([5, 4])

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [5]:
# 不知道多少行,每行10列
stock_change.reshape([-1, 10])

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
         0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

###  array.resize(new_shape) 改变实际数据
- 将数组变为一行,然后按照列数重新切断,分成不同行
- 修改数组本身的形状（需要保持元素个数前后相同）
- 行、列不进行互换

In [6]:
stock_change.resize([10, 2])
stock_change.shape

(10, 2)

In [7]:
stock_change

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574]])

## array.flatten() / array.ravel() 展平数据

In [9]:
stock_change.flatten()

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
        0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [ ]:
stock_change.ravel()

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
        0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [11]:
stock_change_ = torch.from_numpy(stock_change)
stock_change_

tensor([[ 1.7641,  0.4002],
        [ 0.9787,  2.2409],
        [ 1.8676, -0.9773],
        [ 0.9501, -0.1514],
        [-0.1032,  0.4106],
        [ 0.1440,  1.4543],
        [ 0.7610,  0.1217],
        [ 0.4439,  0.3337],
        [ 1.4941, -0.2052],
        [ 0.3131, -0.8541]], dtype=torch.float64)

In [12]:
stock_change_.flatten()

tensor([ 1.7641,  0.4002,  0.9787,  2.2409,  1.8676, -0.9773,  0.9501, -0.1514,
        -0.1032,  0.4106,  0.1440,  1.4543,  0.7610,  0.1217,  0.4439,  0.3337,
         1.4941, -0.2052,  0.3131, -0.8541], dtype=torch.float64)

In [13]:
stock_change_.ravel()

tensor([ 1.7641,  0.4002,  0.9787,  2.2409,  1.8676, -0.9773,  0.9501, -0.1514,
        -0.1032,  0.4106,  0.1440,  1.4543,  0.7610,  0.1217,  0.4439,  0.3337,
         1.4941, -0.2052,  0.3131, -0.8541], dtype=torch.float64)