In [1]:
import matplotlib.pyplot as plt
import numpy as np

## 形状修改

In [2]:
stock_change = np.random.normal(0, 1, (4, 5))

###  数组.reshape(shape, order) 不改变实际数据
- 将数组变为一行,然后按照列数重新切断,分成不同行
- 返回一个具有相同数据域，但shape不一样的视图
- 行、列不进行互换

In [3]:
stock_change

array([[ 0.25039431,  0.70667208, -1.33872455, -0.64909687, -1.6498176 ],
       [-0.78682022, -1.45516223,  1.90928985, -1.73756013, -0.3036893 ],
       [-0.01158256,  0.8418156 ,  0.25184198,  0.61047642,  0.15620136],
       [ 1.12128959,  0.67902333,  0.62488147,  0.87878523, -0.33199807]])

In [4]:
# 在转换形状的时候，一定要注意数组的元素匹配
stock_change.reshape([5,4])

array([[ 0.25039431,  0.70667208, -1.33872455, -0.64909687],
       [-1.6498176 , -0.78682022, -1.45516223,  1.90928985],
       [-1.73756013, -0.3036893 , -0.01158256,  0.8418156 ],
       [ 0.25184198,  0.61047642,  0.15620136,  1.12128959],
       [ 0.67902333,  0.62488147,  0.87878523, -0.33199807]])

In [5]:
# 不知道多少行,每行10列
stock_change.reshape([-1,10])

array([[ 0.25039431,  0.70667208, -1.33872455, -0.64909687, -1.6498176 ,
        -0.78682022, -1.45516223,  1.90928985, -1.73756013, -0.3036893 ],
       [-0.01158256,  0.8418156 ,  0.25184198,  0.61047642,  0.15620136,
         1.12128959,  0.67902333,  0.62488147,  0.87878523, -0.33199807]])

###  数组.resize(new_shape) 改变实际数据
- 将数组变为一行,然后按照列数重新切断,分成不同行
- 修改数组本身的形状（需要保持元素个数前后相同）
- 行、列不进行互换

In [6]:
stock_change.resize([10, 2])
stock_change.shape

(10, 2)

In [7]:
stock_change

array([[ 0.25039431,  0.70667208],
       [-1.33872455, -0.64909687],
       [-1.6498176 , -0.78682022],
       [-1.45516223,  1.90928985],
       [-1.73756013, -0.3036893 ],
       [-0.01158256,  0.8418156 ],
       [ 0.25184198,  0.61047642],
       [ 0.15620136,  1.12128959],
       [ 0.67902333,  0.62488147],
       [ 0.87878523, -0.33199807]])

###  数组转置 .T

- 数组的转置
- 将数组的行、列进行互换

In [9]:
stock_change.T.shape

(2, 10)

In [10]:
stock_change

array([[ 0.25039431,  0.70667208],
       [-1.33872455, -0.64909687],
       [-1.6498176 , -0.78682022],
       [-1.45516223,  1.90928985],
       [-1.73756013, -0.3036893 ],
       [-0.01158256,  0.8418156 ],
       [ 0.25184198,  0.61047642],
       [ 0.15620136,  1.12128959],
       [ 0.67902333,  0.62488147],
       [ 0.87878523, -0.33199807]])

##  类型修改

###  数组.astype(type)

- 返回修改了类型之后的数组

In [11]:
stock_change.astype(np.int32)

array([[ 0,  0],
       [-1,  0],
       [-1,  0],
       [-1,  1],
       [-1,  0],
       [ 0,  0],
       [ 0,  0],
       [ 0,  1],
       [ 0,  0],
       [ 0,  0]])

### 数组.tostring([order])或者数组.tobytes([order])

- 构造包含数组中原始数据字节的Python字节

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[12, 3, 34], [5, 6, 7]]])
arr.tobytes()

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x0c\x00\x00\x00\x03\x00\x00\x00"\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00'