In [1]:
import matplotlib.pyplot as plt
import numpy as np

# 形状修改

In [2]:
np.random.seed(0)
x = np.random.normal(0, 1, (4, 5))
x

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

##  array.reshape(shape, order) 拷贝副本

- 将数组变为一行,然后按照列数重新切断,分成不同行
- 返回一个具有相同数据域，但shape不一样的视图
- 行、列不进行互换

In [3]:
x.reshape([5, 4])

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [4]:
x.reshape([-1, 10])

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
         0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [5]:
x
# 原数据未被修改

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

##  array.resize(new_shape) 修改原数据

- 将数组变为一行,然后按照列数重新切断,分成不同行
- 修改数组本身的形状（需要保持元素个数前后相同）
- 行、列不进行互换

In [6]:
x.resize([10, 2])

In [7]:
x
# 原数据被修改了

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574]])

## array.flatten() 展平数据 拷贝副本

In [8]:
x.flatten()

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
        0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [9]:
x
# 原数据未被修改

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574]])

## array.ravel() 展平数据 修改原数据

a数组的元素将按照这种索引顺序进行读取。

'C'表示按照行主序，即C语言风格的顺序进行索引，最后一个轴的索引变化最快，第一个轴的索引变化最慢。

'F'表示按照列主序，即Fortran风格的顺序进行索引，第一个索引变化最快，最后一个索引变化最慢。

注意，'C'和'F'选项不考虑底层数组的内存布局，仅指轴索引的顺序。

'A'表示如果a在内存中是Fortran连续的，则按照Fortran风格的索引顺序读取元素，否则按照C风格的顺序。

'K'表示按照它们在内存中出现的顺序读取元素，除非步长为负时数据会被反转。

默认情况下，使用'C'索引顺序。

In [10]:
x.ravel()

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
        0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [11]:
x
# 没有修改原数据

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574]])

In [16]:
# 'C'表示按照行主序，即C语言风格的顺序进行索引，最后一个轴的索引变化最快，第一个轴的索引变化最慢。
x.ravel("C")

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
        0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [14]:
# 'F'表示按照列主序，即Fortran风格的顺序进行索引，第一个索引变化最快，最后一个索引变化最慢。
x.ravel("F")

array([ 1.76405235,  0.97873798,  1.86755799,  0.95008842, -0.10321885,
        0.14404357,  0.76103773,  0.44386323,  1.49407907,  0.3130677 ,
        0.40015721,  2.2408932 , -0.97727788, -0.15135721,  0.4105985 ,
        1.45427351,  0.12167502,  0.33367433, -0.20515826, -0.85409574])

In [15]:
# 'A'表示如果a在内存中是Fortran连续的，则按照Fortran风格的索引顺序读取元素，否则按照C风格的顺序。
x.ravel("A")

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
        0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [17]:
# 'K'表示按照它们在内存中出现的顺序读取元素，除非步长为负时数据会被反转。
x.ravel("K")

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
        0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])