In [1]:
import numpy as np

In [22]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

# tile 重复数据(重复整个序列)

In [23]:
np.tile(x, reps=3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [24]:
np.tile(x, reps=[1, 3])

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [25]:
np.tile(x, reps=[3, 1])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

# repeat 重复数据(相邻重复) 类似`torch.repeat_interleave`

In [26]:
# 如果不传 axis 参数, 则默认复制后拉平
np.repeat(x, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [31]:
np.repeat(x, 3, axis=0)
# 注意和tile不同,这个的重复是紧邻的重复,repeat是重复整个序列

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [32]:
np.tile(x, reps=[3, 1])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [35]:
np.repeat(x, 3, axis=1)
# 注意和tile不同,这个的重复是紧邻的重复,repeat是重复整个序列

array([[0, 0, 0, 1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4, 5, 5, 5]])

In [34]:
np.tile(x, reps=[1, 3])

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])