In [6]:
import numpy as np
import torch

# array.T 二维数据转置

In [2]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [7]:
a_ = torch.from_numpy(a)
a_

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)

In [8]:
a_.T

tensor([[0, 3],
        [1, 4],
        [2, 5]], dtype=torch.int32)

# np.swapaxes(array, axis1, axis2) 交换axis1和axis2轴, torch中的transpose

In [4]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
np.swapaxes(b, 0, 1)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [9]:
b_ = torch.from_numpy(b)
b_

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=torch.int32)

In [10]:
b_.transpose(0, 1)

tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]], dtype=torch.int32)

# np.swapaxes(array, (axis...)) 按照顺序重新排列轴, torch中的permute

In [11]:
np.transpose(b, (1, 2, 0))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [12]:
b_.permute(1, 2, 0)

tensor([[[ 0, 12],
         [ 1, 13],
         [ 2, 14],
         [ 3, 15]],

        [[ 4, 16],
         [ 5, 17],
         [ 6, 18],
         [ 7, 19]],

        [[ 8, 20],
         [ 9, 21],
         [10, 22],
         [11, 23]]], dtype=torch.int32)