In [3]:
import numpy as np

## 数组的去重	np.unique()

In [4]:
x = np.array(
    [
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [4, 5],
        [5, 6],
    ]
)

In [5]:
np.unique(x)

array([1, 2, 3, 4, 5, 6])

In [6]:
# 可以指定维度,同时处理多维数据
np.unique(x, axis=0)

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [7]:
np.unique(x, axis=1)

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [4, 5],
       [5, 6]])