In [37]:
import numpy as np

# 逻辑运算

In [38]:
x: np.ndarray = np.arange(20).reshape(2, 10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [39]:
x > 5

array([[False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [40]:
y = x.copy()
y[y > 5] = -1
y

array([[ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

# np.all()

In [41]:
np.all(x > 5)

False

# np.any()

In [42]:
np.any(x > 5)

True

# np.where(三元运算符)

np.where() 以元组形式输出满足条件的列表索引

In [43]:
# 条件满足为1,否则为0
np.where(x > 5, 1, 0)

array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
# 返回索引
np.where(x > 5)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64))

In [45]:
x[np.where(x > 5)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# np.argwhere() 输出的直接是满足要求的元素的坐标索引，多出一个axis

In [46]:
np.argwhere(x > 5)

array([[0, 6],
       [0, 7],
       [0, 8],
       [0, 9],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [1, 6],
       [1, 7],
       [1, 8],
       [1, 9]], dtype=int64)

In [47]:
# 这样是错误的(对于一维数据没区别)
x[np.argwhere(x > 5)]

IndexError: index 6 is out of bounds for axis 0 with size 2

In [48]:
# 这样才正确,因为多了维度,index维度是几维的,就在最后维度划分为几份
x[np.argwhere(x > 5)[:, 0], np.argwhere(x > 5)[:, 1]]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
# 这样才正确,因为多了维度,index维度是几维的,就在最后维度划分为几份
x[np.argwhere(x > 5)[..., 0], np.argwhere(x > 5)[..., 1]]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# 复合逻辑

## np.logical_and 与

In [50]:
np.logical_and(x > 5, x < 15)

array([[False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False]])

In [51]:
# same
(x > 5) & (x < 15)

array([[False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False]])

In [52]:
np.all(np.logical_and(x > 5, x < 15) == (x > 5) & (x < 15))

True

In [53]:
np.where(np.logical_and(x > 5, x < 15), 1, 0)

array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

### reduce

In [54]:
# 创建一个布尔数组
arr = np.array([True, True, False, True])

# 使用 np.logical_and.reduce 函数对数组中的元素进行逻辑与操作
np.logical_and.reduce(arr)

False

In [55]:
# 创建一个空数组
empty_arr = np.array([])

# 创建一个只包含一个元素的数组
single_element_arr = np.array([True])

# 使用 np.logical_and.reduce 函数对这两个数组进行操作
print(np.logical_and.reduce(empty_arr))             # 输出结果为 True，因为空数组被视为 True
print(np.logical_and.reduce(single_element_arr))    # 输出结果为 True，因为只包含一个 True 元素

True
True


In [56]:
# 第一个参数支持使用多个数组
np.logical_and.reduce([x > 5, x < 15], axis=0)

array([[False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False]])

### outer 外积

In [57]:
# 创建两个数组
a = np.array([True, False])
b = np.array([True, True, False])

# 使用 np.logical_and.outer 函数计算逻辑与结果矩阵
np.logical_and.outer(a, b)

array([[ True,  True, False],
       [False, False, False]])

## np.logical_or 或

In [58]:
np.logical_or(x <= 5, x >= 15)

array([[ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True]])

In [59]:
# same
(x <= 5) | (x >= 15)

array([[ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True]])

In [60]:
np.all(np.logical_or(x <= 5, x >= 15) == (x <= 5) | (x >= 15))

True

In [61]:
np.where(np.logical_or(x <= 5, x >= 15), 1, 0)

array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]])

In [62]:
# logical_or 是 logical_and 的反操作
np.logical_and(x > 5, x < 15) == ~np.logical_or(x <= 5, x >= 15)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

### reduce

In [63]:
# 创建一个布尔数组
arr = np.array([True, True, False, True])

# 使用 np.logical_and.reduce 函数对数组中的元素进行逻辑与操作
np.logical_or.reduce(arr)

True

In [64]:
# 创建一个空数组
empty_arr = np.array([])

# 创建一个只包含一个元素的数组
single_element_arr = np.array([True])

# 使用 np.logical_and.reduce 函数对这两个数组进行操作
print(np.logical_or.reduce(empty_arr))          # 输出结果为 False
print(np.logical_or.reduce(single_element_arr)) # 输出结果为 True，因为只包含一个 True 元素

False
True


In [65]:
# 第一个参数支持使用多个数组
np.logical_or.reduce([x <= 5, x >= 15], axis=0)

array([[ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True]])

### outer 外积

In [66]:
# 创建两个数组
a = np.array([True, False])
b = np.array([True, True, False])

# 使用 np.logical_and.outer 函数计算逻辑与结果矩阵
np.logical_or.outer(a, b)

array([[ True,  True,  True],
       [ True,  True, False]])

## np.logical_not 非

In [67]:
# 前后顺序不同有影响
np.logical_not(x > 5, x < 15)

array([[ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [68]:
# 前后顺序不同有影响
np.logical_not(x < 15, x > 5)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True]])

In [69]:
np.where(np.logical_not(x > 5, x < 15), 1, 0)

array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### reduce 不支持

In [70]:
# not 不支持 reduce
np.logical_not.reduce([x > 5, x < 15], axis=0)

ValueError: reduce only supported for binary functions

### outer 外积 不支持

In [71]:
# 创建两个数组
a = np.array([True, False])
b = np.array([True, True, False])

# 使用 np.logical_and.outer 函数计算逻辑与结果矩阵
np.logical_not.outer(a, b)

ValueError: outer product only supported for binary functions

## np.logical_xor 异或

如果a、b两个值不相同，则异或结果为1。

如果a、b两个值相同，异或结果为0。

In [72]:
np.logical_xor(x > 5, x < 15)

array([[ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True]])

In [73]:
np.where(np.logical_xor(x > 5, x < 15), 1, 0)

array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]])

In [74]:
# logical_xor 是 logical_and 的反操作
np.logical_and(x > 5, x < 15) == ~np.logical_xor(x > 5, x < 15)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

### reduce

In [75]:
# 创建一个布尔数组
arr = np.array([True, True, False, True])

# 使用 np.logical_and.reduce 函数对数组中的元素进行逻辑与操作
np.logical_xor.reduce(arr)

True

In [76]:
# 创建一个空数组
empty_arr = np.array([])

# 创建一个只包含一个元素的数组
single_element_arr = np.array([True])

# 使用 np.logical_and.reduce 函数对这两个数组进行操作
print(np.logical_xor.reduce(empty_arr))             # 输出结果为 False
print(np.logical_xor.reduce(single_element_arr))    # 输出结果为 True，因为只包含一个 True 元素

False
True


In [77]:
# 第一个参数支持使用多个数组
np.logical_xor.reduce([x > 5, x < 15], axis=0)

array([[ True,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True]])

### outer 外积

In [78]:
# 创建两个数组
a = np.array([True, False])
b = np.array([True, True, False])

# 使用 np.logical_and.outer 函数计算逻辑与结果矩阵
np.logical_xor.outer(a, b)

array([[False, False,  True],
       [ True,  True, False]])