In [1]:
import matplotlib.pyplot as plt
import numpy as np

## 数组运算

In [2]:
# 生成10名同学，5门功课的数据
score = np.random.randint(40, 100, (10, 5))
# 取出最后4名同学的成绩，用于逻辑判断
test_score = score[6:, 0:5]
test_score

array([[74, 67, 63, 75, 62],
       [44, 51, 45, 95, 77],
       [71, 49, 62, 89, 69],
       [95, 61, 79, 50, 40]])

### 统计运算

进行统计的时候，axis 轴的取值并不一定，Numpy中不同的API轴的值都不一样，在这里，axis 0代表列, axis 1代表行去进行统计

In [3]:
# 指定列 去统计
temp = score[:4, 0:5]
# 这样只找出一个最大值
np.max(temp)

99

In [4]:
print("前四名学生,各科成绩的最大分：{}".format(np.max(temp, axis=0)))
print("前四名学生,各科成绩的最小分：{}".format(np.min(temp, axis=0)))
print("前四名学生,各科成绩波动情况：{}".format(np.std(temp, axis=0)))
print("前四名学生,各科成绩的平均分：{}".format(np.mean(temp, axis=0)))

前四名学生,各科成绩的最大分：[83 99 97 78 88]
前四名学生,各科成绩的最小分：[45 45 41 68 55]
前四名学生,各科成绩波动情况：[13.71814492 19.56240016 20.27775875  4.09267639 13.31117951]
前四名学生,各科成绩的平均分：[61.25 73.75 73.25 74.5  65.25]


如果需要统计出某科最高分对应的是哪个同学？

In [5]:
# argmax 最大值下标
print("前四名学生，各科成绩最高分对应的学生下标：{}".format(np.argmax(temp, axis=0)))

前四名学生，各科成绩最高分对应的学生下标：[0 1 0 0 0]


In [6]:
#median(a, axis)    中位数
np.median(temp)

72.0

In [7]:
# mean(a, axis, dtype)    平均值
np.mean(temp, axis=0)

array([61.25, 73.75, 73.25, 74.5 , 65.25])

In [8]:
# std(a, axis, dtype)    标准差
np.std(temp, axis=0)

array([13.71814492, 19.56240016, 20.27775875,  4.09267639, 13.31117951])

In [9]:
# var(a, axis, dtype)    方差
np.var(temp, axis=0)

array([188.1875, 382.6875, 411.1875,  16.75  , 177.1875])

## 数组间运算

### 数组与数的运算

In [10]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# 每个数都相加
a + 4

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [12]:
# 每个数都除以2
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

### 数组与数组的运算

In [13]:
arr1 = np.array([[1, 2, 3, 4],[3, 4, 5, 6]])
arr2 = np.array([[1, 2, 3, 4],[3, 4, 5, 6]])
arr1 + arr2

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

##### 广播机制

In [14]:
arr1 = np.array([[0], [1], [2], [3]])
arr1.shape

(4, 1)

In [15]:
arr2 = np.array([1,2,3])
arr2.shape

(3,)

In [16]:
arr1 + arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [17]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [18]:
arr1 + arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])