In [2]:
import numpy as np

np.random.seed(43)

In [3]:
a = np.array([8, 9.0])
b = np.array([3.0])
c = np.array([3, 2.0])

# np.add 加

In [4]:
np.add(a, b), a + b

(array([11., 12.]), array([11., 12.]))

In [5]:
np.add(a, c), a + c

(array([11., 11.]), array([11., 11.]))

# np.subtract 减

In [6]:
np.subtract(a, b), a - b

(array([5., 6.]), array([5., 6.]))

In [7]:
np.subtract(a, c), a - c

(array([5., 7.]), array([5., 7.]))

# np.multiply 乘

In [8]:
np.multiply(a, b), a * b

(array([24., 27.]), array([24., 27.]))

In [9]:
np.multiply(a, c), a * c

(array([24., 18.]), array([24., 18.]))

# np.divide 除

In [10]:
np.divide(a, b), a / b

(array([2.66666667, 3.        ]), array([2.66666667, 3.        ]))

In [11]:
np.divide(a, c), a / c

(array([2.66666667, 4.5       ]), array([2.66666667, 4.5       ]))

# np.mod 取余数

In [12]:
np.mod(a, b), a % b

(array([2., 0.]), array([2., 0.]))

In [13]:
np.mod(a, c), a % c

(array([2., 1.]), array([2., 1.]))

# np.abs 绝对值

In [16]:
d = np.arange(-5, 5)
d

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [17]:
np.abs(d)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

# np.negative 相反数

In [18]:
np.negative(d)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4])

# 数组运算

In [6]:
# 生成10名同学，5门功课的数据
score = np.random.randint(40, 100, (10, 5))
# 取出最后4名同学的成绩，用于逻辑判断
test_score = score[6:, 0:5]
test_score

array([[80, 93, 72, 43, 74],
       [81, 83, 65, 69, 88],
       [94, 98, 66, 93, 61],
       [61, 80, 50, 67, 98]])

## 统计运算

进行统计的时候，axis 轴的取值并不一定，Numpy中不同的API轴的值都不一样，在这里，axis 0代表列, axis 1代表行去进行统计

In [7]:
# 指定列 去统计
temp = score[:4, 0:5]
# 这样只找出一个最大值
np.max(temp)

93

In [8]:
print("前四名学生,各科成绩的最大分：{}".format(np.max(temp, axis=0)))
print("前四名学生,各科成绩的最小分：{}".format(np.min(temp, axis=0)))
print("前四名学生,各科成绩波动情况：{}".format(np.std(temp, axis=0)))
print("前四名学生,各科成绩的平均分：{}".format(np.mean(temp, axis=0)))

前四名学生,各科成绩的最大分：[87 88 93 93 74]
前四名学生,各科成绩的最小分：[51 42 41 52 44]
前四名学生,各科成绩波动情况：[15.73809074 16.54350326 20.52285312 16.32482772 11.92424002]
前四名学生,各科成绩的平均分：[66.25 66.75 64.75 80.   57.75]


如果需要统计出某科最高分对应的是哪个同学？

In [9]:
# argmax 最大值下标
print("前四名学生，各科成绩最高分对应的学生下标：{}".format(np.argmax(temp, axis=0)))

前四名学生，各科成绩最高分对应的学生下标：[3 2 2 1 0]


In [10]:
# median(a, axis)    中位数
np.median(temp)

68.5

In [11]:
# mean(a, axis, dtype)    平均值
np.mean(temp, axis=0)

array([66.25, 66.75, 64.75, 80.  , 57.75])

In [12]:
# std(a, axis, dtype)    标准差
np.std(temp, axis=0)

array([15.73809074, 16.54350326, 20.52285312, 16.32482772, 11.92424002])

In [13]:
# var(a, axis, dtype)    方差
np.var(temp, axis=0)

array([247.6875, 273.6875, 421.1875, 266.5   , 142.1875])

## 数组间运算

### 数组与数的运算

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 每个数都相加
a + 4

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [16]:
# 每个数都除以2
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

## 数组与数组的运算

In [17]:
arr1 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])
arr1 + arr2

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

### 广播机制

In [18]:
arr1 = np.array([[0], [1], [2], [3]])
arr1.shape

(4, 1)

In [19]:
arr2 = np.array([1, 2, 3])
arr2.shape

(3,)

In [20]:
arr1 + arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [21]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [22]:
arr1 + arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])