In [1]:
import numpy as np
np.random.seed(43)

In [2]:
x = np.random.random(10).reshape(2, 5)
x

array([[0.11505457, 0.60906654, 0.13339096, 0.24058962, 0.32713906],
       [0.85913749, 0.66609021, 0.54116221, 0.02901382, 0.7337483 ]])

# 累加 cumsum

In [3]:
np.cumsum(x)

array([0.11505457, 0.72412111, 0.85751207, 1.09810169, 1.42524075,
       2.28437824, 2.95046845, 3.49163066, 3.52064449, 4.25439278])

In [4]:
np.cumsum(x, axis=0)

array([[0.11505457, 0.60906654, 0.13339096, 0.24058962, 0.32713906],
       [0.97419206, 1.27515675, 0.67455318, 0.26960344, 1.06088735]])

In [5]:
np.cumsum(x, axis=1)

array([[0.11505457, 0.72412111, 0.85751207, 1.09810169, 1.42524075],
       [0.85913749, 1.5252277 , 2.06638992, 2.09540374, 2.82915204]])

# 累乘 prod

In [6]:
np.prod(x)

4.850422463245135e-06

In [7]:
# axis: 选择谁,谁消失
np.prod(x, axis=0)

array([0.09884769, 0.40569326, 0.07218615, 0.00698042, 0.24003772])

In [8]:
# axis: 选择谁,谁消失
np.prod(x, axis=1)

array([0.00073571, 0.00659288])

In [9]:
# 和axis=1相同
np.prod(x[0]), np.prod(x[1])

(0.0007357059947558263, 0.006592881528517302)

In [11]:
# 可以设定一个初始值，与输入数组中的元素相乘
np.prod(x, initial=10)

4.850422463245134e-05

In [12]:
# 选择特定的元素相乘
np.prod([1., np.nan, 3.], where=[True, False, True])

3.0

# 数组运算

In [6]:
# 生成10名同学，5门功课的数据
score = np.random.randint(40, 100, (10, 5))
# 取出最后4名同学的成绩，用于逻辑判断
test_score = score[6:, 0:5]
test_score

array([[80, 93, 72, 43, 74],
       [81, 83, 65, 69, 88],
       [94, 98, 66, 93, 61],
       [61, 80, 50, 67, 98]])

## 统计运算

进行统计的时候，axis 轴的取值并不一定，Numpy中不同的API轴的值都不一样，在这里，axis 0代表列, axis 1代表行去进行统计

In [7]:
# 指定列 去统计
temp = score[:4, 0:5]
# 这样只找出一个最大值
np.max(temp)

93

In [8]:
print("前四名学生,各科成绩的最大分：{}".format(np.max(temp, axis=0)))
print("前四名学生,各科成绩的最小分：{}".format(np.min(temp, axis=0)))
print("前四名学生,各科成绩波动情况：{}".format(np.std(temp, axis=0)))
print("前四名学生,各科成绩的平均分：{}".format(np.mean(temp, axis=0)))

前四名学生,各科成绩的最大分：[87 88 93 93 74]
前四名学生,各科成绩的最小分：[51 42 41 52 44]
前四名学生,各科成绩波动情况：[15.73809074 16.54350326 20.52285312 16.32482772 11.92424002]
前四名学生,各科成绩的平均分：[66.25 66.75 64.75 80.   57.75]


如果需要统计出某科最高分对应的是哪个同学？

In [9]:
# argmax 最大值下标
print("前四名学生，各科成绩最高分对应的学生下标：{}".format(np.argmax(temp, axis=0)))

前四名学生，各科成绩最高分对应的学生下标：[3 2 2 1 0]


In [10]:
#median(a, axis)    中位数
np.median(temp)

68.5

In [11]:
# mean(a, axis, dtype)    平均值
np.mean(temp, axis=0)

array([66.25, 66.75, 64.75, 80.  , 57.75])

In [12]:
# std(a, axis, dtype)    标准差
np.std(temp, axis=0)

array([15.73809074, 16.54350326, 20.52285312, 16.32482772, 11.92424002])

In [13]:
# var(a, axis, dtype)    方差
np.var(temp, axis=0)

array([247.6875, 273.6875, 421.1875, 266.5   , 142.1875])

## 数组间运算

### 数组与数的运算

In [14]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 每个数都相加
a + 4

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [16]:
# 每个数都除以2
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

## 数组与数组的运算

In [17]:
arr1 = np.array([[1, 2, 3, 4],[3, 4, 5, 6]])
arr2 = np.array([[1, 2, 3, 4],[3, 4, 5, 6]])
arr1 + arr2

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

### 广播机制

In [18]:
arr1 = np.array([[0], [1], [2], [3]])
arr1.shape

(4, 1)

In [19]:
arr2 = np.array([1,2,3])
arr2.shape

(3,)

In [20]:
arr1 + arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [21]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [22]:
arr1 + arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])