In [1]:
import matplotlib.pyplot as plt
import numpy as np

## 数组运算

### 逻辑运算

In [2]:
# 生成10名同学，5门功课的数据
score = np.random.randint(40, 100, (10, 5))
# 取出最后4名同学的成绩，用于逻辑判断
test_score = score[6:, 0:5]
test_score

array([[64, 71, 74, 59, 43],
       [60, 71, 59, 76, 89],
       [91, 87, 53, 58, 68],
       [68, 59, 44, 72, 82]])

In [3]:
# 逻辑判断, 如果成绩大于60就标记为True 否则为False
test_score > 60

array([[ True,  True,  True, False, False],
       [False,  True, False,  True,  True],
       [ True,  True, False, False,  True],
       [ True, False, False,  True,  True]])

In [4]:
# BOOL赋值, 将满足条件的设置为指定的值-布尔索引
test_score[test_score > 60] = 1
#est_score[test_score <= 60] = 0  这样全为0, 因为不为1,就小于等于60
test_score

array([[ 1,  1,  1, 59, 43],
       [60,  1, 59,  1,  1],
       [ 1,  1, 53, 58,  1],
       [ 1, 59, 44,  1,  1]])

### 通用判断函数

#### np.all()

In [5]:
score[0:2, :]

array([[93, 88, 65, 98, 73],
       [60, 42, 65, 64, 78]])

In [6]:
# 判断前2名同学的成绩[0:2, :]是否全及格
np.all(score[0:2, :] > 60)

False

#### np.any()

In [7]:
# 判断前两2同学的成绩[0:2, :]是否有大于90分的
np.any(score[0:2, :] > 80)

True

### np.where（三元运算符）

#### np.where()

In [8]:
# 判断前四名学生,前四门课程中，成绩中大于60的置为1，否则为0
temp = score[:4, :4]
np.where(temp > 60, 1, 0)

array([[1, 1, 1, 1],
       [0, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 1, 0, 1]])

#### 复合逻辑需要结合np.logical_and和np.logical_or使用

In [9]:
np.logical_and(temp > 60, temp < 90)

array([[False,  True,  True, False],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [ True, False, False,  True]])

In [10]:
# 判断前四名学生,前四门课程中，成绩中大于60且小于90的换为1，否则为0
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)

array([[0, 1, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 0, 0, 1]])

In [11]:
# 判断前四名学生,前四门课程中，成绩中大于90或小于60的换为1，否则为0
np.where(np.logical_or(temp > 60, temp < 90), 1, 0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 统计运算

进行统计的时候，axis 轴的取值并不一定，Numpy中不同的API轴的值都不一样，在这里，axis 0代表列, axis 1代表行去进行统计

In [12]:
# 指定列 去统计
temp = score[:4, 0:5]
# 这样只找出一个最大值
np.max(temp)

98

In [13]:

print("前四名学生,各科成绩的最大分：{}".format(np.max(temp, axis=0)))
print("前四名学生,各科成绩的最小分：{}".format(np.min(temp, axis=0)))
print("前四名学生,各科成绩波动情况：{}".format(np.std(temp, axis=0)))
print("前四名学生,各科成绩的平均分：{}".format(np.mean(temp, axis=0)))

前四名学生,各科成绩的最大分：[93 92 74 98 78]
前四名学生,各科成绩的最小分：[51 42 52 64 41]
前四名学生,各科成绩波动情况：[15.66045976 20.83266666  7.84219357 12.19631092 14.84082208]
前四名学生,各科成绩的平均分：[67.5 70.  64.  79.5 66.5]


如果需要统计出某科最高分对应的是哪个同学？

In [14]:
# argmax 最大值下标
print("前四名学生，各科成绩最高分对应的学生下标：{}".format(np.argmax(temp, axis=0)))

前四名学生，各科成绩最高分对应的学生下标：[0 3 2 0 1]


In [15]:
#median(a, axis)    中位数
np.median(temp)

69.5

In [16]:
# mean(a, axis, dtype)    平均值
np.mean(temp, axis=0)

array([67.5, 70. , 64. , 79.5, 66.5])

In [17]:
# std(a, axis, dtype)    标准差
np.std(temp, axis=0)

array([15.66045976, 20.83266666,  7.84219357, 12.19631092, 14.84082208])

In [18]:
# var(a, axis, dtype)    方差
np.var(temp, axis=0)

array([245.25, 434.  ,  61.5 , 148.75, 220.25])

## 数组间运算

### 数组与数的运算

In [19]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# 每个数都相加
a + 4

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [21]:
# 每个数都除以2
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

### 数组与数组的运算

In [22]:
arr1 = np.array([[1, 2, 3, 4],[3, 4, 5, 6]])
arr2 = np.array([[1, 2, 3, 4],[3, 4, 5, 6]])
arr1 + arr2

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

##### 广播机制

In [23]:
arr1 = np.array([[0], [1], [2], [3]])
arr1.shape

(4, 1)

In [24]:
arr2 = np.array([1,2,3])
arr2.shape

(3,)

In [26]:
arr1 + arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [27]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [28]:
arr1 + arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])