In [1]:
import matplotlib.pyplot as plt
import numpy as np

## 数组运算

### 逻辑运算

In [2]:
# 生成10名同学，5门功课的数据
score = np.random.randint(40, 100, (10, 5))
# 取出最后4名同学的成绩，用于逻辑判断
test_score = score[6:, 0:5]
test_score

array([[80, 85, 85, 83, 71],
       [48, 45, 89, 74, 95],
       [74, 44, 62, 77, 93],
       [72, 78, 83, 88, 64]])

In [3]:
# 逻辑判断, 如果成绩大于60就标记为True 否则为False
test_score > 60

array([[ True,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [4]:
# BOOL赋值, 将满足条件的设置为指定的值-布尔索引
test_score[test_score > 60] = 1
#est_score[test_score <= 60] = 0  这样全为0, 因为不为1,就小于等于60
test_score

array([[ 1,  1,  1,  1,  1],
       [48, 45,  1,  1,  1],
       [ 1, 44,  1,  1,  1],
       [ 1,  1,  1,  1,  1]])

### 通用判断函数

#### np.all()

In [5]:
score[0:2, :]

array([[41, 47, 56, 86, 79],
       [68, 83, 79, 86, 82]])

In [6]:
# 判断前2名同学的成绩[0:2, :]是否全及格
np.all(score[0:2, :] > 60)

False

#### np.any()

In [7]:
# 判断前两2同学的成绩[0:2, :]是否有大于90分的
np.any(score[0:2, :] > 80)

True

### np.where（三元运算符）

#### np.where() 以元组形式输出满足条件的列表索引

In [27]:
# 判断前四名学生,前四门课程中，成绩中大于60的置为1，否则为0
temp = score[:4, :4]
temp

array([[41, 47, 56, 86],
       [68, 83, 79, 86],
       [42, 83, 92, 85],
       [95, 92, 81, 64]])

In [28]:
# 条件满足为1,否则为0
np.where(temp > 60, 1, 0)

array([[0, 0, 0, 1],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
np.where(temp > 60)

(array([0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3], dtype=int64),
 array([3, 0, 1, 2, 3, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [30]:
temp[np.where(temp > 60)]

array([86, 68, 83, 79, 86, 83, 92, 85, 95, 92, 81, 64])

#### np.argwhere() 输出的直接是满足要求的元素的坐标索引，多出一个axis

In [31]:
np.argwhere(temp > 60)

array([[0, 3],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3]], dtype=int64)

In [32]:
# 这样是错误的
temp[np.argwhere(temp > 60)]

array([[[41, 47, 56, 86],
        [95, 92, 81, 64]],

       [[68, 83, 79, 86],
        [41, 47, 56, 86]],

       [[68, 83, 79, 86],
        [68, 83, 79, 86]],

       [[68, 83, 79, 86],
        [42, 83, 92, 85]],

       [[68, 83, 79, 86],
        [95, 92, 81, 64]],

       [[42, 83, 92, 85],
        [68, 83, 79, 86]],

       [[42, 83, 92, 85],
        [42, 83, 92, 85]],

       [[42, 83, 92, 85],
        [95, 92, 81, 64]],

       [[95, 92, 81, 64],
        [41, 47, 56, 86]],

       [[95, 92, 81, 64],
        [68, 83, 79, 86]],

       [[95, 92, 81, 64],
        [42, 83, 92, 85]],

       [[95, 92, 81, 64],
        [95, 92, 81, 64]]])

In [34]:
# 这样才正确,因为多了维度
temp[np.argwhere(temp > 60)[:,0], np.argwhere(temp > 60)[:,1]]

array([86, 68, 83, 79, 86, 83, 92, 85, 95, 92, 81, 64])

#### 复合逻辑需要结合np.logical_and和np.logical_or使用

In [9]:
np.logical_and(temp > 60, temp < 90)

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [False, False,  True,  True]])

In [10]:
# 判断前四名学生,前四门课程中，成绩中大于60且小于90的换为1，否则为0
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)

array([[0, 0, 0, 1],
       [1, 1, 1, 1],
       [0, 1, 0, 1],
       [0, 0, 1, 1]])

In [11]:
# 判断前四名学生,前四门课程中，成绩中大于90或小于60的换为1，否则为0
np.where(np.logical_or(temp > 60, temp < 90), 1, 0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])