In [1]:
import numpy as np

In [2]:
np.random.seed(43)

# 逻辑运算

In [3]:
# 生成10名同学，5门功课的数据
score = np.random.randint(40, 100, (10, 5))
# 取出最后4名同学的成绩，用于逻辑判断
test_score = score[6:, 0:5]
test_score

array([[93, 52, 64, 87, 72],
       [50, 88, 49, 74, 88],
       [92, 44, 96, 68, 49],
       [47, 60, 87, 80, 93]])

In [4]:
# 逻辑判断, 如果成绩大于60就标记为True 否则为False
test_score > 60

array([[ True, False,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True, False,  True,  True, False],
       [False, False,  True,  True,  True]])

In [5]:
# BOOL赋值, 将满足条件的设置为指定的值-布尔索引
test_score[test_score > 60] = 1
#est_score[test_score <= 60] = 0  这样全为0, 因为不为1,就小于等于60
test_score

array([[ 1, 52,  1,  1,  1],
       [50,  1, 49,  1,  1],
       [ 1, 44,  1,  1, 49],
       [47, 60,  1,  1,  1]])

# np.all()

In [6]:
score[0:2, :]

array([[44, 40, 89, 61, 98],
       [56, 91, 57, 99, 67]])

In [7]:
# 判断前2名同学的成绩[0:2, :]是否全及格
np.all(score[0:2, :] > 60)

False

# np.any()

In [8]:
# 判断前两2同学的成绩[0:2, :]是否有大于90分的
np.any(score[0:2, :] > 80)

True

# np.allclose 判断两组数据是否近似 返回1个True/False

In [9]:
q = k = v = np.random.random((1, 196, 768))

In [10]:
attn1 = q @ k.swapaxes(-2, -1)
attn1.shape

(1, 196, 196)

In [11]:
attn2 = np.einsum("b p c, b k c -> b p k", q, k)
attn2.shape

(1, 196, 196)

In [12]:
np.all(attn1 == attn2)

False

In [13]:
# param:
#   array1
#   array2
#   rtol: 相对宽容度
#   atol: 绝对宽容度
np.allclose(attn1, attn2, rtol=1e-6, atol=1e-6)

True

# np.isclose 判断两组数据是否近似,返回每个值的对比结果

In [14]:
# param:
#   array1
#   array2
#   rtol: 相对宽容度
#   atol: 绝对宽容度
np.isclose(attn1, attn2, rtol=1e-6, atol=1e-6)

array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])

In [15]:
np.all(np.isclose(attn1, attn2, rtol=1e-6, atol=1e-6))

True

# np.where(三元运算符)

np.where() 以元组形式输出满足条件的列表索引

In [16]:
# 判断前四名学生,前四门课程中，成绩中大于60的置为1，否则为0
temp = score[:4, :4]
temp

array([[44, 40, 89, 61],
       [56, 91, 57, 99],
       [42, 86, 70, 63],
       [75, 90, 99, 51]])

In [17]:
# 条件满足为1,否则为0
np.where(temp > 60, 1, 0)

array([[0, 0, 1, 1],
       [0, 1, 0, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 0]])

In [18]:
np.where(temp > 60)

(array([0, 0, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([2, 3, 1, 3, 1, 2, 3, 0, 1, 2], dtype=int64))

In [19]:
temp[np.where(temp > 60)]

array([89, 61, 91, 99, 86, 70, 63, 75, 90, 99])

# np.argwhere() 输出的直接是满足要求的元素的坐标索引，多出一个axis

In [20]:
np.argwhere(temp > 60)

array([[0, 2],
       [0, 3],
       [1, 1],
       [1, 3],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 0],
       [3, 1],
       [3, 2]], dtype=int64)

In [21]:
# 这样是错误的
temp[np.argwhere(temp > 60)]

array([[[44, 40, 89, 61],
        [42, 86, 70, 63]],

       [[44, 40, 89, 61],
        [75, 90, 99, 51]],

       [[56, 91, 57, 99],
        [56, 91, 57, 99]],

       [[56, 91, 57, 99],
        [75, 90, 99, 51]],

       [[42, 86, 70, 63],
        [56, 91, 57, 99]],

       [[42, 86, 70, 63],
        [42, 86, 70, 63]],

       [[42, 86, 70, 63],
        [75, 90, 99, 51]],

       [[75, 90, 99, 51],
        [44, 40, 89, 61]],

       [[75, 90, 99, 51],
        [56, 91, 57, 99]],

       [[75, 90, 99, 51],
        [42, 86, 70, 63]]])

In [22]:
# 这样才正确,因为多了维度,index维度是几维的,就在最后维度划分为几份
temp[np.argwhere(temp > 60)[:, 0], np.argwhere(temp > 60)[:, 1]]

array([89, 61, 91, 99, 86, 70, 63, 75, 90, 99])

In [23]:
# 这样才正确,因为多了维度,index维度是几维的,就在最后维度划分为几份
temp[np.argwhere(temp > 60)[..., 0], np.argwhere(temp > 60)[..., 1]]

array([89, 61, 91, 99, 86, 70, 63, 75, 90, 99])

# 复合逻辑需要结合np.logical_and和np.logical_or使用

In [24]:
np.logical_and(temp > 60, temp < 90)

array([[False, False,  True,  True],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True, False, False, False]])

In [25]:
# 判断前四名学生,前四门课程中，成绩中大于60且小于90的换为1，否则为0
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)

array([[0, 0, 1, 1],
       [0, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0]])

In [26]:
# 判断前四名学生,前四门课程中，成绩中大于90或小于60的换为1，否则为0
np.where(np.logical_or(temp > 60, temp < 90), 1, 0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])