In [1]:
import matplotlib.pyplot as plt
import numpy as np

# 矩阵运算 matmul dot

In [2]:
a = np.array([[80, 86],
              [82, 80],
              [85, 78],
              [90, 90],
              [86, 82],
              [82, 90],
              [78, 80],
              [92, 94]])
# b一定要写成这样, 里面的0.7和0.3不加中括号的话结果是一行,不是多行
b = np.array([[0.7], [0.3]])
np.matmul(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [3]:
np.dot(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [4]:
c = 10
# dot支持矩阵和数字相乘
np.dot(c, a)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [5]:
# matmul不支持矩阵和数字相乘
np.matmul(c, a)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)