In [1]:
import numpy as np

# np.clip()

In [3]:
x = np.random.randint(-10, 10, (2, 10))
x

array([[ -6,   5,   5,  -8,  -4,   9, -10,   5,  -8,   2],
       [-10,  -7,   4,  -6,  -1,  -3,   5,  -3,   0,  -2]])

## np.clip(array, min, max) 限制上下值

In [10]:
y = np.clip(x, -5, 5)
y

array([[-5,  5,  5, -5, -4,  5, -5,  5, -5,  2],
       [-5, -5,  4, -5, -1, -3,  5, -3,  0, -2]])

## np.minimum(array, max) np.maximum(array, min) 可以实现clip

In [16]:
# 找比5小的
y1 = np.minimum(x, 5)

In [22]:
# 找比-5大的
y2 = np.maximum(y1, -5)
y2

array([[-5,  5,  5, -5, -4,  5, -5,  5, -5,  2],
       [-5, -5,  4, -5, -1, -3,  5, -3,  0, -2]])

In [23]:
np.all(y == y2)

True

# pytorch类似api

In [17]:
import torch

In [18]:
x1 = torch.from_numpy(x)
x1

tensor([[ -6,   5,   5,  -8,  -4,   9, -10,   5,  -8,   2],
        [-10,  -7,   4,  -6,  -1,  -3,   5,  -3,   0,  -2]], dtype=torch.int32)

## torch.clamp(tensor, min, max)

In [25]:
y3 = torch.clamp(x1, -5, 5)
y3 = y3.numpy()
y3

array([[-5,  5,  5, -5, -4,  5, -5,  5, -5,  2],
       [-5, -5,  4, -5, -1, -3,  5, -3,  0, -2]])

## torch.minimum(tensor, max) torch.maximum(tensor, min)

In [27]:
y4 = torch.minimum(x1, torch.tensor(5))

In [29]:
y4 = torch.maximum(x1, torch.tensor(-5))
y4 = y4.numpy()
y4

array([[-5,  5,  5, -5, -4,  9, -5,  5, -5,  2],
       [-5, -5,  4, -5, -1, -3,  5, -3,  0, -2]])

In [31]:
np.all(y2 == y3)

True

In [32]:
np.all(y == y3)

True