In [2]:
import numpy as np

In [3]:
a1 = np.arange(1, 7, 1).reshape(2, 3)
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a2 = np.arange(1, 13, 2).reshape(2, 3)
a2

array([[ 1,  3,  5],
       [ 7,  9, 11]])

# np.concatenate((a1,a2,...), axis=0)

In [5]:
np.concatenate((a1, a2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  3,  5],
       [ 7,  9, 11]])

In [6]:
np.concatenate((a1, a2), axis=1)

array([[ 1,  2,  3,  1,  3,  5],
       [ 4,  5,  6,  7,  9, 11]])

# np.split(x, indices_or_sections=分组数, axis)

In [7]:
x = np.concatenate((a1, a2), axis=0)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  3,  5],
       [ 7,  9, 11]])

In [8]:
np.split(x, indices_or_sections=2, axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 1,  3,  5],
        [ 7,  9, 11]])]

In [9]:
np.split(x, indices_or_sections=3, axis=1)

[array([[1],
        [4],
        [1],
        [7]]),
 array([[2],
        [5],
        [3],
        [9]]),
 array([[ 3],
        [ 6],
        [ 5],
        [11]])]

# stack((a1, a2...), axis) 拼接,axis表示插入新的维度表示原来array

## np.stack((a1, a2...), axis)

In [14]:
np.stack((a1, a2), axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  3,  5],
        [ 7,  9, 11]]])

In [15]:
np.stack((a1, a2), axis=1)

array([[[ 1,  2,  3],
        [ 1,  3,  5]],

       [[ 4,  5,  6],
        [ 7,  9, 11]]])

In [16]:
np.stack((a1, a2), axis=2)

array([[[ 1,  1],
        [ 2,  3],
        [ 3,  5]],

       [[ 4,  7],
        [ 5,  9],
        [ 6, 11]]])

## np.vstack(tuple(a1, a2...)) 竖直拼接

In [14]:
np.vstack((a1, a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  3,  5],
       [ 7,  9, 11]])

## np.hstack(tuple(a1, a2...)) 水平拼接

In [16]:
np.hstack((a1, a2))

array([[ 1,  2,  3,  1,  3,  5],
       [ 4,  5,  6,  7,  9, 11]])