In [2]:
import numpy as np

In [3]:
a = np.array((1, 2, 3.0))
a

array([1., 2., 3.])

# numpy 等号赋值是引用赋值,一个修改另一个也修改,如果不想修改要使用 a.copy() 函数

In [4]:
b = a
b

array([1., 2., 3.])

In [5]:
b += 1
b

array([2., 3., 4.])

In [6]:
a

array([2., 3., 4.])

## [:2] 切片操作也会影响原值

In [7]:
c = a[:2]
c

array([2., 3.])

In [8]:
c /= 10
c

array([0.2, 0.3])

In [9]:
a

array([0.2, 0.3, 4. ])

## 使用 copy 防止修改原值

In [10]:
d = a.copy()
d

array([0.2, 0.3, 4. ])

In [11]:
d *= 2
d

array([0.4, 0.6, 8. ])

In [12]:
a

array([0.2, 0.3, 4. ])