In [1]:
import numpy as np

In [3]:
a = np.arange(0, 12, 1).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 0行和1行交换

In [4]:
a[[1,2], :] = a[[2,1], :]
a

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

## 0列和2列交换

In [5]:
a[:, [0,2]] = a[:, [2,0]]
a

array([[ 2,  1,  0,  3],
       [10,  9,  8, 11],
       [ 6,  5,  4,  7]])