In [12]:
import numpy as np
import torch

# [None] 扩充维度

## numpy 中 类似 expand_dims

In [ ]:
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
print(np.expand_dims(x, 2).shape)
np.expand_dims(x, 2)

(2, 3, 1)


array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [7]:
print(x[:, :, None].shape)
x[:, :, None]

(2, 3, 1)


array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [11]:
print(np.expand_dims(x, [2, 3]).shape)
np.expand_dims(x, [2, 3])

(2, 3, 1, 1)


array([[[[1.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[1.]]]])

In [ ]:
print(x[:, :, None, None].shape)
x[:, :, None, None]

(2, 3, 1, 1)


array([[[[1.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[1.]]]])

## torch 中 类似 unsqueeze

In [23]:
x = torch.ones((2, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [24]:
print(x.unsqueeze(2).shape)
x.unsqueeze(2)

torch.Size([2, 3, 1])


tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

In [25]:
print(x[:, :, None].shape)
x[:, :, None]

torch.Size([2, 3, 1])


tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

In [26]:
print(x.unsqueeze(2).unsqueeze(3).shape)
x.unsqueeze(2).unsqueeze(3)

torch.Size([2, 3, 1, 1])


tensor([[[[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]]]])

In [27]:
print(x[:, :, None, None].shape)
x[:, :, None, None]

torch.Size([2, 3, 1, 1])


tensor([[[[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]]]])