In [1]:
import numpy as np
import torch

# [:1] 会保留维度 [0] 不会保留维度

In [22]:
x = np.ones((2, 5, 3))
x.shape

(2, 5, 3)

In [23]:
# 选择的维度消失
x[0].shape

(5, 3)

In [24]:
# 选择的维度保留
x[:1].shape

(1, 5, 3)

In [25]:
# 选择的维度消失
x[:, 0].shape

(2, 3)

In [26]:
# 选择的维度保留
x[:, :1].shape

(2, 1, 3)

# [None] 扩充维度

## numpy 中 类似 expand_dims reshape

In [2]:
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
print(np.expand_dims(x, 2).shape)
np.expand_dims(x, 2)

(2, 3, 1)


array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [4]:
print(x.reshape(2, 3, 1).shape)
x.reshape(2, 3, 1)

(2, 3, 1)


array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [5]:
print(x[:, :, None].shape)
x[:, :, None]

(2, 3, 1)


array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [6]:
print(np.expand_dims(x, [2, 3]).shape)
np.expand_dims(x, [2, 3])

(2, 3, 1, 1)


array([[[[1.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[1.]]]])

In [7]:
print(x.reshape(2, 3, 1, 1).shape)
x.reshape(2, 3, 1, 1)

(2, 3, 1, 1)


array([[[[1.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[1.]]]])

In [8]:
print(x[:, :, None, None].shape)
x[:, :, None, None]

(2, 3, 1, 1)


array([[[[1.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[1.]]]])

In [9]:
print(np.expand_dims(x, 1).shape)
np.expand_dims(x, 1)

(2, 1, 3)


array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

In [10]:
print(x.reshape(2, 1, 3).shape)
x.reshape(2, 1, 3)

(2, 1, 3)


array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

In [11]:
print(x[:, None, :].shape)
x[:, None, :]

(2, 1, 3)


array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

## torch 中 类似 unsqueeze reshape view

In [12]:
x = torch.ones((2, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
print(x.unsqueeze(2).shape)
x.unsqueeze(2)

torch.Size([2, 3, 1])


tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

In [14]:
print(x.view(2, 3, 1).shape)
x.view(2, 3, 1)

torch.Size([2, 3, 1])


tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

In [15]:
print(x[:, :, None].shape)
x[:, :, None]

torch.Size([2, 3, 1])


tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

In [16]:
print(x.unsqueeze(2).unsqueeze(3).shape)
x.unsqueeze(2).unsqueeze(3)

torch.Size([2, 3, 1, 1])


tensor([[[[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]]]])

In [17]:
print(x.view(2, 3, 1, 1).shape)
x.view(2, 3, 1, 1)

torch.Size([2, 3, 1, 1])


tensor([[[[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]]]])

In [18]:
print(x[:, :, None, None].shape)
x[:, :, None, None]

torch.Size([2, 3, 1, 1])


tensor([[[[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]]]])

In [19]:
print(x.unsqueeze(1).shape)
x.unsqueeze(1)

torch.Size([2, 1, 3])


tensor([[[1., 1., 1.]],

        [[1., 1., 1.]]])

In [20]:
print(x.reshape(2, 1, 3).shape)
x.reshape(2, 1, 3)

torch.Size([2, 1, 3])


tensor([[[1., 1., 1.]],

        [[1., 1., 1.]]])

In [21]:
print(x[:, None, :].shape)
x[:, None, :]

torch.Size([2, 1, 3])


tensor([[[1., 1., 1.]],

        [[1., 1., 1.]]])