In [55]:
import numpy as np
import torch

In [56]:
x = np.arange(1, 11).reshape(2, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
x_t = torch.from_numpy(x)
x_t

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]], dtype=torch.int32)

# 累加 cumsum 返回和原数据相同的序列

In [58]:
np.cumsum(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [59]:
np.cumsum(x, axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 7,  9, 11, 13, 15]])

In [60]:
torch.cumsum(x_t, dim=0)

tensor([[ 1,  2,  3,  4,  5],
        [ 7,  9, 11, 13, 15]])

In [61]:
x_t.cumsum(dim=0)

tensor([[ 1,  2,  3,  4,  5],
        [ 7,  9, 11, 13, 15]])

In [62]:
np.cumsum(x, axis=1)

array([[ 1,  3,  6, 10, 15],
       [ 6, 13, 21, 30, 40]])

In [63]:
torch.cumsum(x_t, dim=1)

tensor([[ 1,  3,  6, 10, 15],
        [ 6, 13, 21, 30, 40]])

# 累乘 prod 返回最终值

In [64]:
# axis: 选择谁,谁消失
np.prod(x, axis=0, keepdims=True)

array([[ 6, 14, 24, 36, 50]])

In [65]:
torch.prod(x_t, dim=0, keepdim=True)

tensor([[ 6, 14, 24, 36, 50]])

In [66]:
np.prod(x, axis=1, keepdims=True)

array([[  120],
       [30240]])

In [67]:
torch.prod(x_t, dim=1, keepdim=True)

tensor([[  120],
        [30240]])

In [68]:
# 可以设定一个初始值，与输入数组中的元素相乘,pytorch每个这个参数
np.prod(x, initial=10)

36288000

In [69]:
# 选择特定的元素相乘,pytorch每个这个参数
np.prod([1.0, np.nan, 3.0], where=[True, False, True])

3.0

# 累乘 cumprod 返回和原数据相同的序列

In [70]:
np.cumprod(x)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [71]:
np.cumsum(x, axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 7,  9, 11, 13, 15]])

In [72]:
torch.cumsum(x_t, dim=0)

tensor([[ 1,  2,  3,  4,  5],
        [ 7,  9, 11, 13, 15]])

In [73]:
np.cumsum(x, axis=1)

array([[ 1,  3,  6, 10, 15],
       [ 6, 13, 21, 30, 40]])

In [74]:
torch.cumsum(x_t, dim=1)

tensor([[ 1,  3,  6, 10, 15],
        [ 6, 13, 21, 30, 40]])