In [1]:
import numpy as np
import torch

# dot 点积

## vector

In [18]:
a = np.array([1, 2])
b = np.array([2, 3])

In [19]:
a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)

In [20]:
a * b
# 与 * 不同

array([2, 6])

In [21]:
np.dot(a, b)

8

In [22]:
a @ b

8

In [24]:
torch.dot(a_t, b_t)

tensor(8, dtype=torch.int32)

In [25]:
a_t @ b_t

tensor(8, dtype=torch.int32)

## matrix (numpy.dot类似矩阵相乘,torch不支持matrix)

In [26]:
a = np.array(
    [
        [1, 2, 3],
        [2, 3, 4],
    ]
)

b = np.array(
    [
        [2, 1, 6],
        [3, 2, 0],
    ]
)

In [27]:
a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)

In [28]:
np.dot(a_t, b_t.T)

array([[22,  7],
       [31, 12]])

In [29]:
# 和矩阵相乘类似
a @ b.T

array([[22,  7],
       [31, 12]])

In [30]:
# torch.dot 只支持 1D 向量,不支持矩阵
torch.dot(a_t, b_t.T)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

# vdot 类似dot,可以处理复数

## matrix 处理多维矩阵会展平

In [32]:
a = np.array([[1, 4], [5, 6]])
b = np.array([[4, 1], [2, 2]])

In [34]:
a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)

In [33]:
np.vdot(a, b)

30

In [35]:
# 不支持多维矩阵,要手动展平数据
torch.vdot(a_t, b_t)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [36]:
# 不支持多维矩阵,要手动展平数据
torch.vdot(a_t.flatten(), b_t.flatten())

tensor(30, dtype=torch.int32)

## 复数

In [41]:
a = np.array([1 + 2j, 3 + 4j])
b = np.array([5 + 6j, 7 + 8j])

In [42]:
a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)

In [39]:
np.vdot(a, b)

(70-8j)

In [ ]:
torch.vdot(a_t, b_t)

tensor(70.-8.j, dtype=torch.complex128)

In [40]:
np.vdot(b, a)

(70+8j)

In [45]:
torch.vdot(b_t, a_t)

tensor(70.+8.j, dtype=torch.complex128)

# inner 内积

## vector

In [52]:
a = np.array([1, 2])
b = np.array([2, 3])

In [53]:
a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)

In [54]:
np.inner(a, b)

8

In [55]:
a @ b

8

In [56]:
torch.inner(a_t, b_t)

tensor(8, dtype=torch.int32)

In [57]:
a_t @ b_t

tensor(8, dtype=torch.int32)

## matrix 矩阵相乘

In [58]:
a = np.array(
    [
        [1, 2, 3],
        [2, 3, 4],
    ]
)

b = np.array(
    [
        [2, 1, 6],
        [3, 2, 0],
    ]
)

In [59]:
a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)

In [61]:
np.inner(a_t, b_t)

array([[22,  7],
       [31, 12]])

In [62]:
# 和矩阵相乘类似
a @ b.T

array([[22,  7],
       [31, 12]])

In [63]:
torch.inner(a_t, b_t)

tensor([[22,  7],
        [31, 12]], dtype=torch.int32)

# outer 内积

## vector

In [64]:
a = np.array([1, 2])
b = np.array([2, 3])

In [68]:
a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)

In [69]:
np.outer(a, b)

array([[2, 3],
       [4, 6]])

In [70]:
torch.outer(a_t, b_t)

tensor([[2, 3],
        [4, 6]], dtype=torch.int32)

## matrix numpy支持,pytorch不支持

In [71]:
a = np.array(
    [
        [1, 2, 3],
        [2, 3, 4],
    ]
)

b = np.array(
    [
        [2, 1, 6],
        [3, 2, 0],
    ]
)

In [72]:
a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)

In [73]:
np.outer(a_t, b_t)

array([[ 2,  1,  6,  3,  2,  0],
       [ 4,  2, 12,  6,  4,  0],
       [ 6,  3, 18,  9,  6,  0],
       [ 4,  2, 12,  6,  4,  0],
       [ 6,  3, 18,  9,  6,  0],
       [ 8,  4, 24, 12,  8,  0]])

In [77]:
# 只支持1D数据
torch.outer(a_t, b_t)

RuntimeError: outer: Expected 1-D argument self, but got 2-D