In [2]:
import numpy as np
import torch

# 二维

In [3]:
a = np.arange(12).reshape(3, 4)
b = np.arange(20).reshape(4, 5)

In [4]:
a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)

In [5]:
a @ b

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462]])

In [6]:
a_t @ b_t

tensor([[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462]], dtype=torch.int32)

In [7]:
np.matmul(a, b)

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462]])

In [9]:
torch.matmul(a_t, b_t)

tensor([[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462]], dtype=torch.int32)

In [10]:
# 只支持2维矩阵
torch.mm(a_t, b_t)

tensor([[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462]], dtype=torch.int32)

# 多维

In [27]:
a = np.arange(12).reshape(1, 3, 4)
b = np.arange(20).reshape(1, 4, 5)

In [28]:
a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)

In [29]:
a @ b

array([[[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462]]])

In [30]:
a_t @ b_t

tensor([[[ 70,  76,  82,  88,  94],
         [190, 212, 234, 256, 278],
         [310, 348, 386, 424, 462]]], dtype=torch.int32)

In [31]:
np.matmul(a, b)

array([[[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462]]])

In [32]:
torch.matmul(a_t, b_t)

tensor([[[ 70,  76,  82,  88,  94],
         [190, 212, 234, 256, 278],
         [310, 348, 386, 424, 462]]], dtype=torch.int32)

In [33]:
# 只支持2维矩阵
torch.mm(a_t, b_t)

RuntimeError: self must be a matrix

In [34]:
# batch mm 前面支持维度, 3D must
torch.bmm(a_t, b_t)

tensor([[[ 70,  76,  82,  88,  94],
         [190, 212, 234, 256, 278],
         [310, 348, 386, 424, 462]]], dtype=torch.int32)