In [1]:
import numpy as np

In [4]:
x = np.random.randint(
    1,
    10,
    [
        2,
        2,
    ],
)
x

array([[7, 4],
       [6, 5]])

In [5]:
y = np.random.randint(
    1,
    10,
    [
        2,
        2,
    ],
)
y

array([[1, 6],
       [1, 5]])

# max

In [8]:
np.max([x, y])

7

In [9]:
# 和 maximum 相同
np.max([x, y], axis=0)

array([[7, 6],
       [6, 5]])

In [10]:
np.max([x, y], axis=1)

array([[7, 5],
       [1, 6]])

# min

In [14]:
np.min([x, y])

1

In [15]:
# 和 minimum 相同
np.min([x, y], axis=0)

array([[1, 4],
       [1, 5]])

In [16]:
np.min([x, y], axis=1)

array([[6, 4],
       [1, 5]])

# maximum 获取相同位置的最大值

In [12]:
np.maximum(x, y)

array([[7, 6],
       [6, 5]])

# maximum 获取相同位置的最小值

In [13]:
np.minimum(x, y)

array([[1, 4],
       [1, 5]])