In [39]:
import numpy as np
from numpy.linalg import norm
import scipy
import torch

In [4]:
x = np.random.normal(0, 1, (2, 3, 4))
x

array([[[-0.94767765,  0.83907246, -0.70195595, -1.30396289],
        [-0.01394255, -1.39636026,  0.42963008, -0.06668142],
        [ 1.83666542,  0.92331114, -0.74779252, -1.4445083 ]],

       [[ 0.41823221,  0.40071131,  1.37640671,  0.88149501],
        [ 1.26559071, -0.39149377, -0.33674793, -1.15566789],
        [-1.04448636,  0.77949581, -0.01701396, -0.29940754]]])

# l2

## 不指定axis

In [5]:
norm(x)

4.561288633640745

In [40]:
scipy.linalg.norm(x)

4.561288633640745

In [12]:
np.sqrt(np.sum(x**2))

4.561288633640745

In [17]:
torch.norm(torch.from_numpy(x))

tensor(4.5613, dtype=torch.float64)

## 指定1个axis

In [24]:
norm(x, ord=2, axis=0)

array([[1.0358625 , 0.92984523, 1.5450688 , 1.57396083],
       [1.26566751, 1.4502032 , 0.54587652, 1.15759003],
       [2.11288703, 1.20835309, 0.74798604, 1.47521155]])

In [41]:
scipy.linalg.norm(x, ord=2, axis=0)

array([[1.0358625 , 0.92984523, 1.5450688 , 1.57396083],
       [1.26566751, 1.4502032 , 0.54587652, 1.15759003],
       [2.11288703, 1.20835309, 0.74798604, 1.47521155]])

In [25]:
np.sqrt(np.sum(x**2, axis=0))

array([[1.0358625 , 0.92984523, 1.5450688 , 1.57396083],
       [1.26566751, 1.4502032 , 0.54587652, 1.15759003],
       [2.11288703, 1.20835309, 0.74798604, 1.47521155]])

In [26]:
torch.norm(torch.from_numpy(x), dim=0)

tensor([[1.0359, 0.9298, 1.5451, 1.5740],
        [1.2657, 1.4502, 0.5459, 1.1576],
        [2.1129, 1.2084, 0.7480, 1.4752]], dtype=torch.float64)

## 指定多个axis结果不对

In [43]:
norm(x, ord=2, axis=(1, 2))

array([2.84333282, 2.10481574])

In [44]:
scipy.linalg.norm(x, ord=2, axis=(1, 2))

array([2.84333282, 2.10481574])

In [45]:
np.sqrt(np.sum(x**2, axis=(1, 2)))

array([3.57853083, 2.82833363])

In [38]:
torch.norm(torch.from_numpy(x), dim=(1, 2))

tensor([3.5785, 2.8283], dtype=torch.float64)

## keepdims = True

In [27]:
norm(x, ord=2, axis=0, keepdims=True)

array([[[1.0358625 , 0.92984523, 1.5450688 , 1.57396083],
        [1.26566751, 1.4502032 , 0.54587652, 1.15759003],
        [2.11288703, 1.20835309, 0.74798604, 1.47521155]]])

In [28]:
np.sqrt(np.sum(x**2, axis=0, keepdims=True))

array([[[1.0358625 , 0.92984523, 1.5450688 , 1.57396083],
        [1.26566751, 1.4502032 , 0.54587652, 1.15759003],
        [2.11288703, 1.20835309, 0.74798604, 1.47521155]]])

In [29]:
torch.norm(torch.from_numpy(x), dim=0, keepdim=True)

tensor([[[1.0359, 0.9298, 1.5451, 1.5740],
         [1.2657, 1.4502, 0.5459, 1.1576],
         [2.1129, 1.2084, 0.7480, 1.4752]]], dtype=torch.float64)

# l1

In [30]:
norm(x, ord=1, axis=1)

array([[2.79828563, 3.15874386, 1.87937854, 2.81515261],
       [2.72830928, 1.57170089, 1.7301686 , 2.33657045]])

In [46]:
scipy.linalg.norm(x, ord=1, axis=1)

array([[2.79828563, 3.15874386, 1.87937854, 2.81515261],
       [2.72830928, 1.57170089, 1.7301686 , 2.33657045]])

In [47]:
np.sum(np.abs(x), axis=1)

array([[2.79828563, 3.15874386, 1.87937854, 2.81515261],
       [2.72830928, 1.57170089, 1.7301686 , 2.33657045]])

In [32]:
torch.norm(torch.from_numpy(x), p=1, dim=1)

tensor([[2.7983, 3.1587, 1.8794, 2.8152],
        [2.7283, 1.5717, 1.7302, 2.3366]], dtype=torch.float64)

## 指定多个axis结果不对

In [49]:
norm(x, ord=1, axis=(1, 2))

array([3.15874386, 2.72830928])

In [50]:
scipy.linalg.norm(x, ord=1, axis=(1, 2))

array([3.15874386, 2.72830928])

In [51]:
np.sum(np.abs(x), axis=(1, 2))

array([10.65156064,  8.36674922])

In [35]:
torch.norm(torch.from_numpy(x), p=1, dim=(1, 2))

tensor([10.6516,  8.3667], dtype=torch.float64)