In [ ]:
import numpy as np
import scipy
from scipy import ndimage, signal
import skimage
import cv2

# np.convolve 只支持一维操作

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
b = np.arange(3)
b

array([0, 1, 2])

In [55]:
np.convolve(a, b)
# 12

array([ 0,  0,  1,  4,  7, 10, 13, 16, 19, 22, 25, 18])

In [56]:
np.convolve(a, b, mode="full")
# 12

array([ 0,  0,  1,  4,  7, 10, 13, 16, 19, 22, 25, 18])

In [57]:
np.convolve(a, b, mode="valid")
# 8 = 10 - 3 + 1

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [58]:
np.convolve(a, b, mode="same")
# 10

array([ 0,  1,  4,  7, 10, 13, 16, 19, 22, 25])

In [59]:
# same 会填充 0
a_ = np.concatenate((np.array([0]), a, np.array([0])), axis=0)
a_

array([0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [60]:
np.convolve(a_, b, mode="valid")
# 10

array([ 0,  1,  4,  7, 10, 13, 16, 19, 22, 25])

## scipy加速计算

In [ ]:
# 执行结果和numpy相同
signal.fftconvolve(a, b)

array([ 0.,  0.,  1.,  4.,  7., 10., 13., 16., 19., 22., 25., 18.])

In [62]:
arr1 = np.random.rand(100000)
arr2 = np.random.rand(100000)

In [63]:
%%timeit
np.convolve(arr1, arr2)
# 速度单位为s

1.54 s ± 25.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
signal.fftconvolve(arr1, arr2)
# 速度单位为ms

8.9 ms ± 347 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# ndimage 支持图片

## 二维图像

In [65]:
image = np.arange(25, dtype=np.float32).reshape(5, 5)
weight = np.arange(9, dtype=np.float32).reshape(3, 3)

In [ ]:
ndimage.convolve(image, weight, mode="reflect")

array([[ 24.,  45.,  81., 117., 144.],
       [ 99., 120., 156., 192., 219.],
       [279., 300., 336., 372., 399.],
       [459., 480., 516., 552., 579.],
       [624., 645., 681., 717., 744.]], dtype=float32)

In [ ]:
ndimage.convolve(image, weight, mode="constant")

array([[  8.,  26.,  41.,  56.,  56.],
       [ 54., 120., 156., 192., 168.],
       [159., 300., 336., 372., 303.],
       [264., 480., 516., 552., 438.],
       [344., 584., 617., 650., 488.]], dtype=float32)

In [ ]:
# cval 代表 mode='constant' 时的填充数值,默认为 0
ndimage.convolve(image, weight, mode="constant", cval=0.0)

array([[  8.,  26.,  41.,  56.,  56.],
       [ 54., 120., 156., 192., 168.],
       [159., 300., 336., 372., 303.],
       [264., 480., 516., 552., 438.],
       [344., 584., 617., 650., 488.]], dtype=float32)

In [ ]:
ndimage.convolve(image, weight, mode="constant", cval=1.0)

array([[ 36.,  47.,  62.,  77.,  80.],
       [ 69., 120., 156., 192., 177.],
       [174., 300., 336., 372., 312.],
       [279., 480., 516., 552., 447.],
       [360., 587., 620., 653., 500.]], dtype=float32)

## 三维图像

### h w c

In [70]:
image1 = np.arange(25 * 2, dtype=np.float32).reshape(5, 5, 2)
weight1 = np.arange(9 * 2, dtype=np.float32).reshape(3, 3, 2)

In [ ]:
result = ndimage.convolve(image1, weight1, mode="constant")
result.shape

(5, 5, 2)

### c h w

In [72]:
image1 = np.arange(25 * 2, dtype=np.float32).reshape(2, 5, 5)
weight1 = np.arange(9 * 2, dtype=np.float32).reshape(2, 3, 3)

In [ ]:
result1 = ndimage.convolve(image, weight, mode="constant")
result1.shape

(5, 5)

# skimage 使用 ndimage.convolve 进行卷积

In [74]:
skimage.filters.convolve(image, weight)

AttributeError: No skimage.filters attribute convolve

# opencv

In [75]:
image.shape

(5, 5)

In [82]:
cv2.filter2D(image, -1, weight, borderType=cv2.BORDER_CONSTANT)

array([[ 88., 142., 175., 208., 136.],
       [210., 312., 348., 384., 240.],
       [345., 492., 528., 564., 345.],
       [480., 672., 708., 744., 450.],
       [232., 304., 319., 334., 184.]], dtype=float32)

In [ ]:
ndimage.convolve(image, weight, mode="constant")

array([[  8.,  26.,  41.,  56.,  56.],
       [ 54., 120., 156., 192., 168.],
       [159., 300., 336., 372., 303.],
       [264., 480., 516., 552., 438.],
       [344., 584., 617., 650., 488.]], dtype=float32)

In [96]:
cv2.filter2D(image, -1, weight, borderType=cv2.BORDER_REFLECT)

array([[120., 147., 183., 219., 240.],
       [285., 312., 348., 384., 405.],
       [465., 492., 528., 564., 585.],
       [645., 672., 708., 744., 765.],
       [720., 747., 783., 819., 840.]], dtype=float32)

In [ ]:
ndimage.convolve(image, weight, mode="reflect")

array([[ 24.,  45.,  81., 117., 144.],
       [ 99., 120., 156., 192., 219.],
       [279., 300., 336., 372., 399.],
       [459., 480., 516., 552., 579.],
       [624., 645., 681., 717., 744.]], dtype=float32)