In [52]:
import numpy as np
from scipy import ndimage
from skimage import filters

# np.convolve 只支持一维操作

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = np.arange(3)
b

array([0, 1, 2])

In [4]:
np.convolve(a, b)
# 12

array([ 0,  0,  1,  4,  7, 10, 13, 16, 19, 22, 25, 18])

In [5]:
np.convolve(a, b, mode="full")
# 12

array([ 0,  0,  1,  4,  7, 10, 13, 16, 19, 22, 25, 18])

In [6]:
np.convolve(a, b, mode="valid")
# 8 = 10 - 3 + 1

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [7]:
np.convolve(a, b, mode="same")
# 10

array([ 0,  1,  4,  7, 10, 13, 16, 19, 22, 25])

In [8]:
# same 会填充 0
a_ = np.concatenate((np.array([0]), a, np.array([0])), axis=0)
a_

array([0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [9]:
np.convolve(a_, b, mode="valid")
# 10

array([ 0,  1,  4,  7, 10, 13, 16, 19, 22, 25])

# ndimage 支持图片

## 二维图像

In [78]:
image = np.arange(25, dtype=np.float32).reshape(5, 5)
weight = np.arange(9, dtype=np.float32).reshape(3, 3)

In [ ]:
ndimage.convolve(image, weight, mode="reflect")

array([[ 24.,  45.,  81., 117., 144.],
       [ 99., 120., 156., 192., 219.],
       [279., 300., 336., 372., 399.],
       [459., 480., 516., 552., 579.],
       [624., 645., 681., 717., 744.]], dtype=float32)

In [68]:
ndimage.convolve(image, weight, mode="constant")

array([[  8.,  26.,  41.,  56.,  56.],
       [ 54., 120., 156., 192., 168.],
       [159., 300., 336., 372., 303.],
       [264., 480., 516., 552., 438.],
       [344., 584., 617., 650., 488.]], dtype=float32)

In [69]:
# cval 代表 mode='constant' 时的填充数值,默认为 0
ndimage.convolve(image, weight, mode="constant", cval=0.0)

array([[  8.,  26.,  41.,  56.,  56.],
       [ 54., 120., 156., 192., 168.],
       [159., 300., 336., 372., 303.],
       [264., 480., 516., 552., 438.],
       [344., 584., 617., 650., 488.]], dtype=float32)

In [70]:
ndimage.convolve(image, weight, mode="constant", cval=1.0)

array([[ 36.,  47.,  62.,  77.,  80.],
       [ 69., 120., 156., 192., 177.],
       [174., 300., 336., 372., 312.],
       [279., 480., 516., 552., 447.],
       [360., 587., 620., 653., 500.]], dtype=float32)

## 三维图像

### h w c

In [71]:
image = np.arange(25 * 2, dtype=np.float32).reshape(5, 5, 2)
weight = np.arange(9 * 2, dtype=np.float32).reshape(3, 3, 2)

In [72]:
result = ndimage.convolve(image, weight, mode="constant")
result.shape

(5, 5, 2)

### c h w

In [73]:
image = np.arange(25 * 2, dtype=np.float32).reshape(2, 5, 5)
weight = np.arange(9 * 2, dtype=np.float32).reshape(2, 3, 3)

In [74]:
result = ndimage.convolve(image, weight, mode="constant")
result.shape

(2, 5, 5)

# skimage 使用 scipy.ndimage.convolve 进行卷积