In [2]:
import numpy as np

# np.diff

NumPy 的 np.diff 函数用于计算输入数组中连续元素之间的差异。

函数概述

np.diff的基本语法如下：

```python
numpy.diff(a, n=1, axis=-1, prepend=np._NoValue, append=np._NoValue)
```

参数说明

- a: 输入数组，支持多维数组。
- n: 整数，表示进行差分的次数。默认为1，即计算一次差分。如果设置为0，则返回原始数组。
- axis: 整数，指定沿哪个轴进行差分，默认是最后一个轴（即axis=-1）。
- prepend: 在计算差分之前，向数组前面添加的值。
- append: 在计算差分之后，向数组后面添加的值。

返回值

返回一个新的数组，包含输入数组元素的n阶差分。输出数组的形状与输入数组相同，但在指定的轴上维度会减少n。

In [6]:
a = np.array([1, 2, 4, 7, 0])
diff = np.diff(a)
print(diff)

[ 1  2  3 -7]


In [11]:
# 获取差异最大的一个 index
max_idx =np.argmax(np.abs(diff))
max_idx

3

In [10]:
a[max_idx]

7

In [12]:
a = np.array([
    [1, 2, 4, 7, 0],
    [1, 3, 7, -2, 4]
])
diff = np.diff(a)
print(diff)

[[ 1  2  3 -7]
 [ 2  4 -9  6]]


In [13]:
a = np.array([
    [1, 2, 4, 7, 0],
    [1, 3, 7, -2, 4]
])
diff = np.diff(a, axis=0)
print(diff)

[[ 0  1  3 -9  4]]
