# np.eye 生成标准矩阵, 可以将值转换为one-hot模式

https://numpy.org/doc/stable/reference/generated/numpy.eye.html

Parameters:
- N: int. one-hot矩阵行数

- M: int, optional. one-hot矩阵列数. If None, defaults to N.

- k: int, optional. Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

- order: {‘C’, ‘F’}, optional. Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.

- like: array_like, optional

In [1]:
import numpy as np

In [2]:
arr = np.array([2, 4, 2, 3, 4, 2, 0, 1, 0, 1])

In [3]:
len(np.unique(arr))

5

In [5]:
eye1 = np.eye(N=len(np.unique(arr)), dtype=np.int32)
eye1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [6]:
# arr取eye中的值,要求arr中的下标不能超过eye的行数
eye1[arr]

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [7]:
arr1 = arr.reshape(2, -1)
arr1

array([[2, 4, 2, 3, 4],
       [2, 0, 1, 0, 1]])

In [8]:
eye1[arr1]

array([[[0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]],

       [[0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0]]])