In [26]:
import numpy as np

np.random.seed(0)

# np.eye 生成标准矩阵, 可以将值转换为one-hot模式

https://numpy.org/doc/stable/reference/generated/numpy.eye.html

Parameters:
- N: int. one-hot矩阵行数

- M: int, optional. one-hot矩阵列数. If None, defaults to N.

- k: int, optional. Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

- order: {‘C’, ‘F’}, optional. Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.

- like: array_like, optional

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr = np.array([2, 4, 2, 3, 4, 2, 0, 1, 0, 1])

In [29]:
len(np.unique(arr))

5

In [30]:
eye1 = np.eye(N=len(np.unique(arr)), dtype=np.int32)
eye1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
# arr取eye中的值,要求arr中的下标不能超过eye的行数
eye1[arr]

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [32]:
arr1 = arr.reshape(2, -1)
arr1

array([[2, 4, 2, 3, 4],
       [2, 0, 1, 0, 1]])

In [33]:
eye1[arr1]

array([[[0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]],

       [[0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0]]])

# np.diag 提取对角线或构造对角线数组

## 传入1d数据就构造2d对角线数组

In [34]:
x = np.ones(3)
print(x)
np.diag(x)

[1. 1. 1.]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
x = np.array([1, 2, 3.0])
print(x)
np.diag(x)

[1. 2. 3.]


array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [36]:
x = np.array([0, 2, 4.0])
print(x)
np.diag(x)

[0. 2. 4.]


array([[0., 0., 0.],
       [0., 2., 0.],
       [0., 0., 4.]])

## 传入2d数据就获取1d对角线的值

In [37]:
x = np.arange(4.0).reshape(2, 2)
print(x)
np.diag(x)

[[0. 1.]
 [2. 3.]]


array([0., 3.])

In [38]:
x = np.arange(9.0).reshape(3, 3)
print(x)
np.diag(x)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


array([0., 4., 8.])

## 参数k的作用

In [39]:
x = np.arange(9.0).reshape(3, 3)
print(x)
np.diag(x, k=0)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


array([0., 4., 8.])

In [40]:
x = np.arange(9.0).reshape(3, 3)
print(x)
print(np.diag(x, k=1))
print(np.diag(x, k=2))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[1. 5.]
[2.]


In [41]:
x = np.arange(9.0).reshape(3, 3)
print(x)
print(np.diag(x, k=-1))
print(np.diag(x, k=-2))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[3. 7.]
[6.]


## 传入非方阵也能获取对角线的值,以最短边长度为最终长度

In [42]:
x = np.random.random((3, 4))
print(x)
np.diag(x)

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]


array([0.5488135 , 0.64589411, 0.79172504])

In [43]:
x = np.random.random((4, 3))
print(x)
np.diag(x)

[[0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]]


array([0.56804456, 0.0202184 , 0.97861834])