In [13]:
import numpy as np

# lexsort

使用一系列的 key 进行排序，最后返回一个排序的index

- keys: keys 是一个序列，包含多个数组或可转换为相同形状的对象。每个数组可以被视为一个排序的列。最后一个键用于主排序，倒数第二个键用于次排序，以此类推。</br>
        keys 是从后往前数的。也就是最后一个 key 相同，就看倒数第二个 key，倒数第二个相同就看倒数第三个 key。

- axis: 指定排序的轴，默认值为 -1，即对最后一个轴进行排序。

In [40]:
a = np.array([[3, 3, 8], [6, 9, 7], [3, 3, 2]])

In [41]:
"""
index = np.lexsort((a[:, 2], a[:, 1], a[:, 0])) 的运行情况：
step-1、首先按照第一列 a[:, 0] 的数值 [3, 6, 3] 升序顺序对每行的位置进行重排, 第一行有两个值相同, 转到step-2
            [[3, 3, 8],        [[3, 3, 8],
             [6, 9, 7],   -->   [3, 3, 2],
             [3, 3, 2]]         [6, 9, 7]]
step-2、第一列数值相同的情况下按照相应位置第二列 a[:, 1] 的值继续排序, 第二列对应位置任然相同, 转到step-3
            [[3, 3, 8],        [[3, 3, 8],
             [6, 9, 7],   -->   [3, 3, 2],
             [3, 3, 2]]         [6, 9, 7]]
step-3、第二列数值相同的情况下按照相应位置第三列 a[:, 2] 的值继续排序
            [[3, 3, 8],        [[3, 3, 2],
             [6, 9, 7],   -->   [3, 3, 8],
             [3, 3, 2]]         [6, 9, 7]]
总结: 第一列的排序结果为[3, 3, 6] 对应的索引值为 [2, 0, 1]
"""
index = np.lexsort((a[:, 2], a[:, 1], a[:, 0]))
index

array([2, 0, 1], dtype=int64)

In [42]:
a[index]  # 按照排序结果重置数组元素的位置

array([[3, 3, 2],
       [3, 3, 8],
       [6, 9, 7]])

In [43]:
"""
直接对矩阵进行排序相当于拆解为

key1 = a[0,:]
key2 = a[1,:]
key3 = a[2,:]  # 最后一行为主排序序列

index = np.lexsort(a) 等效为: index = np.lexsort((a[0,:], a[1,:], a[2,:]))

"""
np.lexsort(a)

array([2, 0, 1], dtype=int64)

In [46]:
np.lexsort((a[0, :], a[1, :], a[2, :]))

array([2, 0, 1], dtype=int64)

# box 测试

In [45]:
boxes = np.array(
    [
        [0, 2, 4, 5],
        [0, 0, 5, 5],
        [6, 6, 10, 10],
        [1, 6, 7, 8],
        [6, 4, 9, 8],
        [1, 8, 12, 10],
    ]
)
boxes

array([[ 0,  2,  4,  5],
       [ 0,  0,  5,  5],
       [ 6,  6, 10, 10],
       [ 1,  6,  7,  8],
       [ 6,  4,  9,  8],
       [ 1,  8, 12, 10]])

In [25]:
index = np.lexsort((boxes[:, 3], boxes[:, 2], boxes[:, 1], boxes[:, 0]))
index

array([1, 0, 3, 5, 4, 2], dtype=int64)

In [26]:
boxes[index]

array([[ 0,  0,  5,  5],
       [ 0,  2,  4,  5],
       [ 1,  6,  7,  8],
       [ 1,  8, 12, 10],
       [ 6,  4,  9,  8],
       [ 6,  6, 10, 10]])

In [22]:
index = np.lexsort((boxes[:, 0], boxes[:, 1], boxes[:, 2], boxes[:, 3]))
index

array([0, 1, 3, 4, 2, 5], dtype=int64)

In [23]:
boxes[index]

array([[ 0,  2,  4,  5],
       [ 0,  0,  5,  5],
       [ 1,  6,  7,  8],
       [ 6,  4,  9,  8],
       [ 6,  6, 10, 10],
       [ 1,  8, 12, 10]])