In [14]:
import numpy as np
np.random.seed(0)

In [15]:
x = np.random.random((2, 2))
x

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [16]:
y = np.random.random((2, 3))
y

array([[0.4236548 , 0.64589411, 0.43758721],
       [0.891773  , 0.96366276, 0.38344152]])

In [17]:
save_path1 = "test.npy"
save_path2 = "test.npz"

# np.save

In [20]:
# 保存ndarray
np.save(save_path1, x)

In [21]:
np.load(save_path1)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

# np.savez

In [26]:
# 保存字典
np.savez(save_path2, x=x, y=y)

In [27]:
np.load(save_path2)["x"]

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [28]:
np.load(save_path2)["y"]

array([[0.4236548 , 0.64589411, 0.43758721],
       [0.891773  , 0.96366276, 0.38344152]])