In [17]:
import numpy as np

In [18]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# 并集 union1d

In [19]:
np.union1d(array1, array2)

array([1, 2, 3, 4, 5, 6, 7])

# 交集 intersect1d

In [20]:
np.intersect1d(array1, array2)

array([3, 4, 5])

# 差集 setdiff1d 2个数据前后顺序有差别

In [21]:
np.setdiff1d(array1, array2)

array([1, 2])

In [22]:
# 颠倒2个array顺序结果变化,以前一个为准
np.setdiff1d(array2, array1)

array([6, 7])

# 长数据测试

In [25]:
data = np.arange(10000)
data[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
index = np.random.choice(range(10000), 10000, replace=True)
index.sort()
index[:10]

array([1, 2, 3, 3, 3, 4, 5, 6, 6, 7])

In [27]:
unique_index = np.array(list(set(index)))
unique_index.shape

(6312,)

In [28]:
unique_index[:10]

array([ 1,  2,  3,  4,  5,  6,  7, 10, 11, 12])

In [29]:
np.setdiff1d(data, unique_index).shape

(3688,)

In [30]:
np.intersect1d(data, unique_index).shape

(6312,)

In [32]:
# 交集 == unique_index
(np.intersect1d(data, unique_index) == unique_index).sum()

6312