In [33]:
import numpy as np

# np.pad 填充数组边缘

https://numpy.org/doc/stable/reference/generated/numpy.pad.html

In [34]:
x = np.arange(25).reshape(5, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
# pad_width = left/right/top/bottom
np.pad(x, pad_width=1, mode="constant", constant_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  9,  0],
       [ 0, 10, 11, 12, 13, 14,  0],
       [ 0, 15, 16, 17, 18, 19,  0],
       [ 0, 20, 21, 22, 23, 24,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [36]:
# pad_width = ((top/left, bottom/right)
np.pad(x, pad_width=[1, 2], mode="constant", constant_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  4,  0,  0],
       [ 0,  5,  6,  7,  8,  9,  0,  0],
       [ 0, 10, 11, 12, 13, 14,  0,  0],
       [ 0, 15, 16, 17, 18, 19,  0,  0],
       [ 0, 20, 21, 22, 23, 24,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [37]:
# pad_width = ((top, bottom), (left, right))
np.pad(x, pad_width=[[0, 1], [2, 3]], mode="constant", constant_values=0)

array([[ 0,  0,  0,  1,  2,  3,  4,  0,  0,  0],
       [ 0,  0,  5,  6,  7,  8,  9,  0,  0,  0],
       [ 0,  0, 10, 11, 12, 13, 14,  0,  0,  0],
       [ 0,  0, 15, 16, 17, 18, 19,  0,  0,  0],
       [ 0,  0, 20, 21, 22, 23, 24,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [38]:
# Pads with the edge values of array.
np.pad(x, pad_width=1, mode="edge")

array([[ 0,  0,  1,  2,  3,  4,  4],
       [ 0,  0,  1,  2,  3,  4,  4],
       [ 5,  5,  6,  7,  8,  9,  9],
       [10, 10, 11, 12, 13, 14, 14],
       [15, 15, 16, 17, 18, 19, 19],
       [20, 20, 21, 22, 23, 24, 24],
       [20, 20, 21, 22, 23, 24, 24]])

In [39]:
# Pads with the linear ramp between end_value and the array edge value.
np.pad(x, pad_width=1, mode="linear_ramp", end_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  9,  0],
       [ 0, 10, 11, 12, 13, 14,  0],
       [ 0, 15, 16, 17, 18, 19,  0],
       [ 0, 20, 21, 22, 23, 24,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [40]:
# Pads with the maximum value of all or part of the vector along each axis.
np.pad(x, pad_width=1, mode="maximum")

array([[24, 20, 21, 22, 23, 24, 24],
       [ 4,  0,  1,  2,  3,  4,  4],
       [ 9,  5,  6,  7,  8,  9,  9],
       [14, 10, 11, 12, 13, 14, 14],
       [19, 15, 16, 17, 18, 19, 19],
       [24, 20, 21, 22, 23, 24, 24],
       [24, 20, 21, 22, 23, 24, 24]])

In [41]:
# Pads with the minimum value of all or part of the vector along each axis.
np.pad(x, pad_width=1, mode="minimum")

array([[ 0,  0,  1,  2,  3,  4,  0],
       [ 0,  0,  1,  2,  3,  4,  0],
       [ 5,  5,  6,  7,  8,  9,  5],
       [10, 10, 11, 12, 13, 14, 10],
       [15, 15, 16, 17, 18, 19, 15],
       [20, 20, 21, 22, 23, 24, 20],
       [ 0,  0,  1,  2,  3,  4,  0]])

In [42]:
# Pads with the mean value of all or part of the vector along each axis.
np.pad(x, pad_width=1, mode="mean")

array([[12, 10, 11, 12, 13, 14, 12],
       [ 2,  0,  1,  2,  3,  4,  2],
       [ 7,  5,  6,  7,  8,  9,  7],
       [12, 10, 11, 12, 13, 14, 12],
       [17, 15, 16, 17, 18, 19, 17],
       [22, 20, 21, 22, 23, 24, 22],
       [12, 10, 11, 12, 13, 14, 12]])

In [43]:
# Pads with the median value of all or part of the vector along each axis.
np.pad(x, pad_width=1, mode="median")

array([[12, 10, 11, 12, 13, 14, 12],
       [ 2,  0,  1,  2,  3,  4,  2],
       [ 7,  5,  6,  7,  8,  9,  7],
       [12, 10, 11, 12, 13, 14, 12],
       [17, 15, 16, 17, 18, 19, 17],
       [22, 20, 21, 22, 23, 24, 22],
       [12, 10, 11, 12, 13, 14, 12]])

In [44]:
# Pads with the reflection of the vector mirrored on the first and last values of the vector along each axis.
np.pad(x, pad_width=1, mode="reflect", reflect_type="even")

array([[ 6,  5,  6,  7,  8,  9,  8],
       [ 1,  0,  1,  2,  3,  4,  3],
       [ 6,  5,  6,  7,  8,  9,  8],
       [11, 10, 11, 12, 13, 14, 13],
       [16, 15, 16, 17, 18, 19, 18],
       [21, 20, 21, 22, 23, 24, 23],
       [16, 15, 16, 17, 18, 19, 18]])

In [45]:
# Pads with the reflection of the vector mirrored along the edge of the array.
np.pad(x, pad_width=1, mode="symmetric", reflect_type="odd")

array([[ 0,  0,  1,  2,  3,  4,  4],
       [ 0,  0,  1,  2,  3,  4,  4],
       [ 5,  5,  6,  7,  8,  9,  9],
       [10, 10, 11, 12, 13, 14, 14],
       [15, 15, 16, 17, 18, 19, 19],
       [20, 20, 21, 22, 23, 24, 24],
       [20, 20, 21, 22, 23, 24, 24]])

In [46]:
# Pads with the wrap of the vector along the axis.
# The first values are used to pad the end and the end values are used to pad the beginning.
np.pad(x, pad_width=1, mode="wrap")

array([[24, 20, 21, 22, 23, 24, 20],
       [ 4,  0,  1,  2,  3,  4,  0],
       [ 9,  5,  6,  7,  8,  9,  5],
       [14, 10, 11, 12, 13, 14, 10],
       [19, 15, 16, 17, 18, 19, 15],
       [24, 20, 21, 22, 23, 24, 20],
       [ 4,  0,  1,  2,  3,  4,  0]])

In [47]:
# Pads with undefined values.
np.pad(x, pad_width=1, mode="empty")

array([[ 543716457,  543516788, 1818649970, 1769235301, 1864396399,
        1752440934, 1702240357],
       [1919906915,          0,          1,          2,          3,
                 4,  538976288],
       [1701344288,          5,          6,          7,          8,
                 9, 1864397669],
       [1752440934,         10,         11,         12,         13,
                14,  538976288],
       [ 538976288,         15,         16,         17,         18,
                19, 1701670265],
       [1667854964,         20,         21,         22,         23,
                24,  543716457],
       [ 543516788, 1818649970, 1769235301, 1864396399, 1752440934,
        1702240357, 1919906915]])