In [1]:
import numpy as np

# percentile: 计算一个多维数组的任意百分比分位数，此处的百分位是从小到大排列

## 单维数组

In [2]:
x = np.arange(0, 101)
np.random.shuffle(x)
x

array([  5,  72,   3,  23,  38,   7,  91,  93,   2,  18,  55,  25,  15,
        33,  71,  96,  61,  62,  66,  69,  10,  30,  45,  12,  53,  22,
        65,  68,  52,  99,  46,   8,  85,  49,  40,  86,  41,  16,  19,
        76,  54,  44,  13,  94,  92,  79,  43,   0,  50, 100,  60,  67,
        20,  73,  88,  26,  24,  56,  74,  32,  34,  64,  82,  98,  75,
        77,  17,  84,  58,  81,  27,   4,  35,  51,  42,  78,  29,  90,
        36,  28,  11,  57,  80,  97,   6,  87,  89,  83,  95,  31,  70,
        14,  21,  48,  39,  59,  47,   1,   9,  63,  37])

In [3]:
np.percentile(x, 50)

np.float64(50.0)

In [4]:
np.percentile(x, 0)

np.float64(0.0)

In [5]:
np.percentile(x, 95)

np.float64(95.0)

In [6]:
np.percentile(x, 20.3)

np.float64(20.3)

In [16]:
y = np.logspace(0, 2, 10)
y

array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ])

In [17]:
np.percentile(y, 50)

np.float64(10.329066738480055)

In [18]:
np.percentile(y, 0)

np.float64(1.0)

In [19]:
np.percentile(y, 100)

np.float64(100.0)

In [20]:
np.percentile(y, 95)

np.float64(81.9767912643523)

## 多维数组

In [21]:
z = np.stack([
    np.arange(1, 11),
    np.logspace(0, 2, 10),
], axis=0)
z

array([[  1.        ,   2.        ,   3.        ,   4.        ,
          5.        ,   6.        ,   7.        ,   8.        ,
          9.        ,  10.        ],
       [  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
          7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
         59.94842503, 100.        ]])

In [22]:
np.percentile(z, 50, axis=1)

array([ 5.5       , 10.32906674])