In [1]:
import numpy as np

# percentile/quantile: 计算一个多维数组的任意百分比分位数，此处的百分位是从小到大排列

percentile 使用 [0, 100] 之间的百分比值来计算分位数。

quantile 使用 [0, 1] 之间的分位数来计算百分比值。

## 单维数组

In [2]:
x = np.arange(0, 101)
np.random.shuffle(x)
x

array([ 25,  65,  86,  53,  71,  74,  49,  87,  31,  33,  52,  95,  61,
        19,  48,   0,  56,  67,  97,  43,  69,  24,  75,  76,  41,  83,
         8,  15,  26,  58,   2,  11,  32,  29,  36,   3,  27,  22,  81,
        34,  64,  42,  23,  44,  47,  92,  66,  12,  89,  98,  14,   9,
        94,  39,  38,  51,   7,  82,  99,  85,  90,  72,  28,  73,  54,
        17,  62,  96, 100,  68,  80,  63,  13,  79,  93,  77,  55,  46,
        57,  45,  20,  37,   4,  91,   6,   1,  16,  30,  50,  88,   5,
        10,  59,  35,  18,  78,  21,  40,  84,  60,  70])

In [4]:
np.percentile(x, 50), np.quantile(x, 0.5)

(np.float64(50.0), np.float64(50.0))

In [5]:
np.percentile(x, 0), np.quantile(x, 0)

(np.float64(0.0), np.int64(0))

In [6]:
np.percentile(x, 95), np.quantile(x, 0.95)

(np.float64(95.0), np.float64(95.0))

In [7]:
np.percentile(x, 20.3), np.quantile(x, 0.23)

(np.float64(20.3), np.float64(23.0))

In [9]:
y = np.logspace(0, 2, 10)
y

array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ])

In [ ]:
np.percentile(y, 50), np.quantile(y, 0.5)

(np.float64(10.329066738480055), np.float64(10.329066738480055))

In [ ]:
np.percentile(y, 0), np.quantile(y, 0)

(np.float64(1.0), np.float64(1.0))

In [13]:
np.percentile(y, 100), np.quantile(y, 1)

(np.float64(100.0), np.float64(100.0))

In [14]:
np.percentile(y, 95), np.quantile(y, 0.95)

(np.float64(81.9767912643523), np.float64(81.9767912643523))

## 多维数组

In [16]:
z = np.stack([
    np.arange(1, 11),
    np.logspace(0, 2, 10),
], axis=0)
z

array([[  1.        ,   2.        ,   3.        ,   4.        ,
          5.        ,   6.        ,   7.        ,   8.        ,
          9.        ,  10.        ],
       [  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
          7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
         59.94842503, 100.        ]])

In [17]:
np.percentile(z, 50, axis=1)

array([ 5.5       , 10.32906674])

In [19]:
np.quantile(z, 0.5, axis=1)

array([ 5.5       , 10.32906674])