In [1]:
import numpy as np

# percentile: 计算一个多维数组的任意百分比分位数，此处的百分位是从小到大排列

## 单维数组

In [15]:
x = np.arange(0, 101)
np.random.shuffle(x)
x

array([ 98,  54,   1,  56,  61,  55,  28,  64,  75,  12,   8,  85,  19,
        13,  70,  49,   0,   2,  53,  91,  37,  25,   6,  76,  65,  92,
        72,  36,  38,  84,  45,  77,  30,  44,   5,  80,  46,  69,  97,
        35,  51,  88,  66,  47,  83,  57,  99,  14,  82,  41,  73,  81,
        42,  48,  27,  39,  22,  71,  86, 100,  79,  87,  20,  24,  59,
        16,  58,  78,  62,  23,  96,  74,  43,  60,  26,  15,  94,  18,
        93,  63,  10,   4,  32,  29,  50,  67,  17,  95,  34,  40,  90,
        52,   9,  89,  11,  21,  68,   3,   7,  31,  33])

In [16]:
np.percentile(x, 50)

np.float64(50.0)

In [17]:
np.percentile(x, 0)

np.float64(0.0)

In [18]:
np.percentile(x, 95)

np.float64(95.0)

In [20]:
np.percentile(x, 20.3)

np.float64(20.3)

## 多维数组

In [22]:
y = np.stack([
    np.arange(1, 11),
    np.arange(11, 21),
    np.arange(21, 31),
], axis=0)
y

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [25]:
np.percentile(y, 50, axis=1)

array([ 5.5, 15.5, 25.5])