In [1]:
import numpy as np
import scipy

# toeplitz matrix

In [ ]:
scipy.linalg.toeplitz([0, 1, 2])

array([[0, 1, 2],
       [1, 0, 1],
       [2, 1, 0]])

In [4]:
scipy.linalg.toeplitz([0, 0, 1])

array([[0, 0, 1],
       [0, 0, 0],
       [1, 0, 0]])

In [5]:
# 会把多维数据展平
scipy.linalg.toeplitz([[0, 1, 2], [0, 1, 2]])

array([[0, 1, 2, 0, 1, 2],
       [1, 0, 1, 2, 0, 1],
       [2, 1, 0, 1, 2, 0],
       [0, 2, 1, 0, 1, 2],
       [1, 0, 2, 1, 0, 1],
       [2, 1, 0, 2, 1, 0]])

In [2]:
scipy.linalg.toeplitz(range(5))

array([[0, 1, 2, 3, 4],
       [1, 0, 1, 2, 3],
       [2, 1, 0, 1, 2],
       [3, 2, 1, 0, 1],
       [4, 3, 2, 1, 0]])