In [1]:
import numpy as np
import torch

# [:, 0] 与 [..., 0]

[:, 0]   代表第0维度全取,第1维取下标为0的

[..., 0] 代表取最后的维度下标为0的

In [2]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
# 对于二维数据, [:, 0] [..., 0] 效果相同
a[:, 0]

array([0, 3])

In [4]:
a[..., 0]

array([0, 3])

In [5]:
b = np.arange(12).reshape(2, 2, 3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [6]:
# 对于多维数据, [:, 0] [..., 0] 效果不同
b[:, 0]

array([[0, 1, 2],
       [6, 7, 8]])

In [7]:
b[..., 0]

array([[0, 3],
       [6, 9]])

# [:1] 会保留维度 [0] 不会保留维度

In [8]:
x = np.ones((2, 5, 3))
x.shape

(2, 5, 3)

In [9]:
# 选择的维度消失
x[0].shape

(5, 3)

In [10]:
# 选择的维度保留
x[:1].shape

(1, 5, 3)

In [11]:
# 选择的维度消失
x[:, 0].shape

(2, 3)

In [12]:
# 选择的维度保留
x[:, :1].shape

(2, 1, 3)

# [None] 扩充维度

## numpy 中 类似 expand_dims reshape

In [24]:
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
print(np.expand_dims(x, 0).shape)
np.expand_dims(x, 0)

(1, 2, 3)


array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
print(x.reshape(1, 2, 3).shape)
x.reshape(1, 2, 3)

(1, 2, 3)


array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [30]:
print(x[None, :, :].shape)
x[None, :, :]

(1, 2, 3)


array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
# 如果是在开始添加新的维度, 可以不用写全后面的 `:`
print(x[None, :].shape)
x[None, :]

(1, 2, 3)


array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
print(np.expand_dims(x, [2, 3]).shape)
np.expand_dims(x, [2, 3])

(2, 3, 1, 1)


array([[[[1.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[1.]]]])

In [35]:
print(x.reshape(2, 3, 1, 1).shape)
x.reshape(2, 3, 1, 1)

(2, 3, 1, 1)


array([[[[1.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[1.]]]])

In [36]:
print(x[:, :, None, None].shape)
x[:, :, None, None]

(2, 3, 1, 1)


array([[[[1.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[1.]]]])

In [37]:
print(np.expand_dims(x, 1).shape)
np.expand_dims(x, 1)

(2, 1, 3)


array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

In [38]:
print(x.reshape(2, 1, 3).shape)
x.reshape(2, 1, 3)

(2, 1, 3)


array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

In [40]:
print(x[:, None, :].shape)
x[:, None, :]

(2, 1, 3)


array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

In [42]:
# 可以不用写全后面的 `:`
print(x[:, None].shape)
x[:, None]

(2, 1, 3)


array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

## torch 中 类似 unsqueeze reshape view

In [17]:
x = torch.ones((2, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
print(x.unsqueeze(2).shape)
x.unsqueeze(2)

torch.Size([2, 3, 1])


tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

In [19]:
print(x.view(2, 3, 1).shape)
x.view(2, 3, 1)

torch.Size([2, 3, 1])


tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

In [20]:
print(x[:, :, None].shape)
x[:, :, None]

torch.Size([2, 3, 1])


tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

In [21]:
print(x.unsqueeze(2).unsqueeze(3).shape)
x.unsqueeze(2).unsqueeze(3)

torch.Size([2, 3, 1, 1])


tensor([[[[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]]]])

In [22]:
print(x.view(2, 3, 1, 1).shape)
x.view(2, 3, 1, 1)

torch.Size([2, 3, 1, 1])


tensor([[[[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]]]])

In [23]:
print(x[:, :, None, None].shape)
x[:, :, None, None]

torch.Size([2, 3, 1, 1])


tensor([[[[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]]]])

In [24]:
print(x.unsqueeze(1).shape)
x.unsqueeze(1)

torch.Size([2, 1, 3])


tensor([[[1., 1., 1.]],

        [[1., 1., 1.]]])

In [25]:
print(x.reshape(2, 1, 3).shape)
x.reshape(2, 1, 3)

torch.Size([2, 1, 3])


tensor([[[1., 1., 1.]],

        [[1., 1., 1.]]])

In [26]:
print(x[:, None, :].shape)
x[:, None, :]

torch.Size([2, 1, 3])


tensor([[[1., 1., 1.]],

        [[1., 1., 1.]]])