In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# 生成10名同学，5门功课的数据
score = np.random.randint(40, 100, (10, 5))
score

array([[98, 61, 95, 48, 94],
       [59, 89, 88, 66, 91],
       [90, 55, 82, 78, 91],
       [79, 63, 45, 70, 92],
       [85, 56, 48, 76, 92],
       [53, 54, 48, 98, 85],
       [94, 49, 93, 65, 87],
       [84, 60, 67, 77, 73],
       [73, 97, 93, 59, 54],
       [93, 79, 89, 96, 63]])

In [3]:
# 构造列索引序列
subjects = ["Chinese", "Math", "English", "Sciencs", "Sports"]
# 构造行索引序列
students = [f"stu_{i+1}" for i in range(score.shape[0])]
# 添加行列列索引
score_df = pd.DataFrame(score, columns=subjects, index=students)
score_df

Chinese  Math  English  Sciencs  Sports
stu_1        98    61       95       48      94
stu_2        59    89       88       66      91
stu_3        90    55       82       78      91
stu_4        79    63       45       70      92
stu_5        85    56       48       76      92
stu_6        53    54       48       98      85
stu_7        94    49       93       65      87
stu_8        84    60       67       77      73
stu_9        73    97       93       59      54
stu_10       93    79       89       96      63

# 获取行

## df.head(n)

In [4]:
score_df.head()

Chinese  Math  English  Sciencs  Sports
stu_1       98    61       95       48      94
stu_2       59    89       88       66      91
stu_3       90    55       82       78      91
stu_4       79    63       45       70      92
stu_5       85    56       48       76      92

In [5]:
score_df.head(3)

Chinese  Math  English  Sciencs  Sports
stu_1       98    61       95       48      94
stu_2       59    89       88       66      91
stu_3       90    55       82       78      91

## df.tail(n)

In [6]:
score_df.tail()

Chinese  Math  English  Sciencs  Sports
stu_6        53    54       48       98      85
stu_7        94    49       93       65      87
stu_8        84    60       67       77      73
stu_9        73    97       93       59      54
stu_10       93    79       89       96      63

## df[n:m] 索引获取行数据,只能是切片,不能是单个索引

In [7]:
# 这样是错误的,DataFrame[]里面应该写字段
score_df[2]

KeyError: 2

In [ ]:
score_df[:2]

Chinese  Math  English  Sciencs  Physics
stu_1       97    84       57       52       53
stu_2       95    78       82       62       79

In [ ]:
score_df[2:5]

Chinese  Math  English  Sciencs  Sports
stu_3       83    79       40       62      78
stu_4       53    79       70       40      51
stu_5       54    74       75       74      56

In [ ]:
# 这样是先找前5行,再在返回的结果中找2行
score_df[:5][1:3]

Chinese  Math  English  Sciencs  Sports
stu_2       95    78       82       62      79
stu_3       83    79       40       62      78

In [ ]:
# 错误  不支持切片
score_df[:1, :2]

InvalidIndexError: (slice(None, 1, None), slice(None, 2, None))

# 获取列

## df["列名"], df[["列名1", "列名2"]] 与 df.列名 获取列

In [ ]:
score_df["Chinese"]

stu_1     97
stu_2     95
stu_3     83
stu_4     53
stu_5     54
stu_6     74
stu_7     83
stu_8     85
stu_9     78
stu_10    94
Name: Chinese, dtype: int32

In [ ]:
score_df.Chinese

stu_1     97
stu_2     95
stu_3     83
stu_4     53
stu_5     54
stu_6     74
stu_7     83
stu_8     85
stu_9     78
stu_10    94
Name: Chinese, dtype: int32

In [ ]:
score_df[["Chinese", "Math"]]

Chinese  Math
stu_1        97    84
stu_2        95    78
stu_3        83    79
stu_4        53    79
stu_5        54    74
stu_6        74    90
stu_7        83    73
stu_8        85    52
stu_9        78    81
stu_10       94    42

# 获取行列指定位置

## df["列名"]["行名"]

In [ ]:
score_df["Chinese"]["stu_2"]

95

In [ ]:
score_df.Chinese["stu_2"]

95

In [ ]:
# 获取多列和行不行
score_df[["Chinese", "Math"]]["stu_2"]

KeyError: 'stu_2'

In [ ]:
# 获取列和多行不行
score_df[["Chinese"]][["stu_2", "stu_3"]]

KeyError: "None of [Index(['stu_2', 'stu_3'], dtype='object')] are in the [columns]"

# df.iloc[index, column] 指定 index_name 和 column_number 支持切片

In [ ]:
score_df.iloc[2, 3]

62

In [ ]:
score_df.iloc[:2, :3]

Chinese  Math  English
stu_1       97    84       57
stu_2       95    78       82

In [ ]:
score_df.iloc[:, :3]

Chinese  Math  English
stu_1        97    84       57
stu_2        95    78       82
stu_3        83    79       40
stu_4        53    79       70
stu_5        54    74       75
stu_6        74    90       54
stu_7        83    73       44
stu_8        85    52       81
stu_9        78    81       59
stu_10       94    42       99

# df.loc[index, column] 指定 index_name 和 column_name  支持切片

In [ ]:
score_df.loc["stu_2", "Sports"]

79

In [ ]:
score_df.loc["stu_2":"stu_7", "Math":"Sports"]

Math  English  Sciencs  Sports
stu_2    78       82       62      79
stu_3    79       40       62      78
stu_4    79       70       40      51
stu_5    74       75       74      56
stu_6    90       54       72      56
stu_7    73       44       71      71

In [ ]:
score_df.loc["stu_2":"stu_7", :]

Chinese  Math  English  Sciencs  Sports
stu_2       95    78       82       62      79
stu_3       83    79       40       62      78
stu_4       53    79       70       40      51
stu_5       54    74       75       74      56
stu_6       74    90       54       72      56
stu_7       83    73       44       71      71

# 使用ix组合索引(新版弃用了)

In [ ]:
# 使用ix进行下表和名称组合做引
score_df.ix[0:4, ["Math", "Sports"]]

AttributeError: 'DataFrame' object has no attribute 'ix'

## 推荐使用loc和iloc来获取的方式

In [ ]:
score_df.loc[score_df.index[1:4], ["Math", "Sports"]]

Math  Sports
stu_2    44      74
stu_3    43      41
stu_4    54      41

In [ ]:
score_df.index.get_indexer(["stu_1", "stu_3", "stu_5"])

array([0, 2, 4], dtype=int64)

In [ ]:
score_df.columns.get_indexer(["English", "Sports"])

array([2, 4], dtype=int64)

In [ ]:
score_df.iloc[
    score_df.index.get_indexer(["stu_1", "stu_3", "stu_5"]),
    score_df.columns.get_indexer(["English", "Sports"]),
]

English  Sports
stu_1       48      66
stu_3       98      41
stu_5       89      98