https://plotly.com/python/ml-regression/

In [4]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# plotly.express trendline = ['lowess', 'rolling', 'ewm', 'expanding', 'ols']

In [5]:
tips = px.data.tips()
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
fig = px.scatter(
    data_frame=tips,
    x="total_bill",
    y="tip",
    opacity=0.65,
    trendline="ols",  # ['lowess', 'rolling', 'ewm', 'expanding', 'ols']
    trendline_color_override="darkblue",
)
fig.show()

In [7]:
fig = px.scatter(
    data_frame=tips,
    x="total_bill",
    y="tip",
    opacity=0.65,
    trendline="lowess",  # ['lowess', 'rolling', 'ewm', 'expanding', 'ols']
    trendline_color_override="darkblue",
)
fig.show()

In [8]:
fig = px.scatter(
    data_frame=tips,
    x="total_bill",
    y="tip",
    opacity=0.65,
    trendline="expanding",  # ['lowess', 'rolling', 'ewm', 'expanding', 'ols']
    trendline_color_override="darkblue",
)
fig.show()

# Linear Regression with scikit-learn

## Basic

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
X = tips["total_bill"].values.reshape(-1, 1)
X[:10]

array([[16.99],
       [10.34],
       [21.01],
       [23.68],
       [24.59],
       [25.29],
       [ 8.77],
       [26.88],
       [15.04],
       [14.78]])

In [12]:
y = tips["tip"].values
y[:10]

array([1.01, 1.66, 3.5 , 3.31, 3.61, 4.71, 2.  , 3.12, 1.96, 3.23])

In [13]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [14]:
x_range = np.linspace(X.min(), X.max(), 100)
x_range[:10]

array([3.07      , 3.55222222, 4.03444444, 4.51666667, 4.99888889,
       5.48111111, 5.96333333, 6.44555556, 6.92777778, 7.41      ])

In [15]:
y_range = model.predict(x_range.reshape(-1, 1))
y_range[:10]

array([1.24269488, 1.29334004, 1.34398519, 1.39463035, 1.44527551,
       1.49592066, 1.54656582, 1.59721098, 1.64785613, 1.69850129])

In [16]:
fig = px.scatter(data_frame=tips, x="total_bill", y="tip", opacity=0.65)

fig.add_trace(go.Scatter(x=x_range, y=y_range, name="Regression fit"))

fig.show()

## Model generalization on unseen data

With go.Scatter, you can easily color your plot based on a predefined data split. By coloring the training and the testing data points with different colors, you can easily see if whether the model generalizes well to the test data or not.

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X = tips["total_bill"].values.reshape(-1, 1)
X[:10]

array([[16.99],
       [10.34],
       [21.01],
       [23.68],
       [24.59],
       [25.29],
       [ 8.77],
       [26.88],
       [15.04],
       [14.78]])

In [19]:
y = tips["tip"].values
y[:10]

array([1.01, 1.66, 3.5 , 3.31, 3.61, 4.71, 2.  , 3.12, 1.96, 3.23])

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [21]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [22]:
x_range = np.linspace(X.min(), X.max(), 100)
y_range = model.predict(x_range.reshape(-1, 1))

In [23]:
fig = go.Figure(
    data=[
        go.Scatter(x=X_train.flatten(), y=y_train, name="train", mode="markers"),
        go.Scatter(x=X_test.flatten(), y=y_test, name="test", mode="markers"),
        go.Scatter(x=x_range, y=y_range, name="LinearRegression"),
    ]
)
fig.show()

## Comparing different kNN models parameters

In addition to linear regression, it's possible to fit the same data using k-Nearest Neighbors. When you perform a prediction on a new sample, this model either takes the weighted or un-weighted average of the neighbors. In order to see the difference between those two averaging options, we train a kNN model with both of those parameters, and we plot them in the same way as the previous graph.

Notice how we can combine scatter points with lines using Plotly.py. You can learn more about multiple chart types.

In [24]:
from sklearn.neighbors import KNeighborsRegressor

In [25]:
X = tips.total_bill.values.reshape(-1, 1)
x_range = np.linspace(X.min(), X.max(), 100)
y = tips.tip.values

In [26]:
knn_dist = KNeighborsRegressor(n_neighbors=5, weights="distance")
knn_dist.fit(X, y)

KNeighborsRegressor(weights='distance')

In [27]:
y_dist = knn_dist.predict(x_range.reshape(-1, 1))
y_dist[:10]

array([1.        , 1.4138624 , 1.62397504, 1.72137274, 1.71474015,
       1.52384337, 1.55191571, 2.12714874, 2.47471444, 2.24869412])

In [28]:
knn_uni = KNeighborsRegressor(n_neighbors=5, weights="uniform")
knn_uni.fit(X, y)

KNeighborsRegressor()

In [29]:
y_uni = knn_uni.predict(x_range.reshape(-1, 1))
y_uni[:10]

array([2.03 , 2.03 , 2.03 , 2.03 , 2.03 , 2.118, 2.118, 2.118, 2.206,
       2.206])

In [30]:
fig = px.scatter(
    data_frame=tips,
    x="total_bill",
    y="tip",
    color="sex",
    opacity=0.65,
)

fig.add_traces(
    [
        go.Scatter(x=x_range, y=y_dist, name="distance"),
        go.Scatter(x=x_range, y=y_uni, name="uniform"),
    ]
)

fig.show()

## Displaying PolynomialFeatures using $\LaTeX$

Notice how linear regression fits a straight line, but kNN can take non-linear shapes. Moreover, it is possible to extend linear regression to polynomial regression by using scikit-learn's PolynomialFeatures, which lets you fit a slope for your features raised to the power of n, where n=1,2,3,4 in our example.

With Plotly, it's easy to display latex equations in legend and titles by simply adding $ before and after your equation. This way, you can see the coefficients that our polynomial regression fitted.

In [31]:
from sklearn.preprocessing import PolynomialFeatures

In [32]:
def format_coefs(coefs):
    equation_list = [f"{coef}x^{i}" for i, coef in enumerate(coefs)]
    equation = "$" + " + ".join(equation_list) + "$"

    replace_map = {"x^0": "", "x^1": "x", "+ -": "- "}
    for old, new in replace_map.items():
        equation = equation.replace(old, new)

    return equation

In [33]:
X = tips.total_bill.values.reshape(-1, 1)
x_range = np.linspace(X.min(), X.max(), 100)
y = tips.tip.values

In [34]:
fig = px.scatter(data_frame=tips, x="total_bill", y="tip", opacity=0.65)
for degree in [1, 2, 3, 4]:
    # 数据预处理
    poly = PolynomialFeatures(degree)
    X_ploy = poly.fit_transform(X.reshape(-1, 1))
    x_range_ploy = poly.transform(x_range.reshape(-1, 1))

    # fit
    model = LinearRegression(fit_intercept=False)
    model.fit(X_ploy, y)
    y_poly = model.predict(x_range_ploy)

    equation = format_coefs(model.coef_.round(2))
    fig.add_trace(go.Scatter(x=x_range.squeeze(), y=y_poly, name=equation))
fig.show()

## 3D regression surface with px.scatter_3d and go.Surface

Visualize the decision plane of your model whenever you have more than one variable in your input data. Here, we will use sklearn.svm.SVR, which is a Support Vector Machine (SVM) model specifically designed for regression.

In [35]:
from sklearn.svm import SVR

In [36]:
mesh_size = 0.2
margin = 0

In [37]:
iris = px.data.iris()
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [38]:
X = iris[["sepal_width", "sepal_length"]]
y = iris["petal_width"]

In [39]:
# Condition the model on sepal width and length, predict the petal width
model = SVR(C=1.0)
model.fit(X, y)

SVR()

In [40]:
# Create a mesh grid on which we will run our model
x_min, x_max = X.sepal_width.min() - margin, X.sepal_width.max() + margin
y_min, y_max = X.sepal_length.min() - margin, X.sepal_length.max() + margin

In [41]:
xrange = np.arange(x_min, x_max, mesh_size)
yrange = np.arange(y_min, y_max, mesh_size)
xx, yy = np.meshgrid(xrange, yrange)

In [42]:
# Run model
pred = model.predict(np.c_[xx.flatten(), yy.flatten()])
pred = pred.reshape(xx.shape)
pred.shape

d:\miniconda3\envs\pytorch\Lib\site-packages\sklearn\base.py:465: UserWarning:

X does not have valid feature names, but SVR was fitted with feature names



(18, 13)

In [43]:
fig = px.scatter_3d(data_frame=iris, x="sepal_width", y="sepal_length", z="petal_width")
fig.update_traces(marker=dict(size=5))
fig.add_traces(go.Surface(x=xrange, y=yrange, z=pred, name="pred_surface"))
fig.show()

## Visualizing coefficients for multiple linear regression (MLR)

Visualizing regression with one or two variables is straightforward, since we can respectively plot them with scatter plots and 3D scatter plots. Moreover, if you have more than 2 features, you will need to find alternative ways to visualize your data.

One way is to use bar charts. In our example, each bar indicates the coefficients of our linear regression model for each input feature. Our model was trained on the Iris dataset.

In [44]:
iris = px.data.iris()
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [45]:
X = iris.drop(columns=["petal_width", "species_id"])
X = pd.get_dummies(X, columns=["species"], prefix_sep="=")
y = iris["petal_width"]

In [46]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [47]:
colors = ["Positive" if c > 0 else "Negative" for c in model.coef_]

In [48]:
fig = px.bar(
    x=X.columns,
    y=model.coef_,
    color=colors,
    color_discrete_sequence=["red", "blue"],
    labels=dict(x="Feature", y="Linear coefficient"),
)
fig.show()

## Simple actual vs predicted plot

This example shows you the simplest way to compare the predicted output vs. the actual output. A good model will have most of the scatter dots near the diagonal black line.

In [49]:
iris = px.data.iris()
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [50]:
X = iris[["sepal_width", "sepal_length"]]
y = iris["petal_width"]

In [51]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [52]:
y_pred = model.predict(X)

In [53]:
fig = px.scatter(x=y, y=y_pred, labels={"x": "ground truth", "y": "prediction"})
fig.add_shape(
    type="line",
    line=dict(dash="dash"),
    x0=y.min(),
    y0=y.min(),
    x1=y.max(),
    y1=y.max(),
)
fig.show()

## Enhanced prediction error analysis using plotly.express

Add marginal histograms to quickly diagnoses any prediction bias your model might have. The built-in OLS functionality let you visualize how well your model generalizes by comparing it with the theoretical optimal fit (black dotted line).

In [54]:
iris = px.data.iris()
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [55]:
# Split data into training and test splits
train_idx, test_idx = train_test_split(iris.index, test_size=0.25, random_state=0)

In [56]:
iris["split"] = "train"
iris.loc[test_idx, "split"] = "test"

In [57]:
np.unique(iris["split"])

array(['test', 'train'], dtype=object)

In [58]:
X = iris[["sepal_width", "sepal_length"]]
y = iris["petal_width"]

In [59]:
X_train = iris.loc[train_idx, ["sepal_width", "sepal_length"]]
y_train = iris.loc[train_idx, "petal_width"]

In [60]:
# Condition the model on sepal width and length, predict the petal width
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [61]:
iris["prediction"] = model.predict(X)

In [62]:
fig = px.scatter(
    data_frame=iris,
    x="petal_width",
    y="prediction",
    marginal_x="histogram",
    marginal_y="histogram",
    color="split",
    trendline="ols",
)
fig.update_traces(histnorm="probability", selector={"type": "histogram"})
fig.add_shape(
    type="line", line=dict(dash="dash"), x0=y.min(), y0=y.min(), x1=y.max(), y1=y.max()
)
fig.show()

## Residual plots

Just like prediction error plots, it's easy to visualize your prediction residuals in just a few lines of codes using plotly.express built-in capabilities.

In [63]:
iris = px.data.iris()
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [64]:
# Split data into training and test splits
train_idx, test_idx = train_test_split(iris.index, test_size=0.25, random_state=0)
iris["split"] = "train"
iris.loc[test_idx, "split"] = "test"

In [65]:
X = iris[["sepal_width", "sepal_length"]]
X_train = iris.loc[train_idx, ["sepal_width", "sepal_length"]]
y_train = iris.loc[train_idx, "petal_width"]

In [66]:
# Condition the model on sepal width and length, predict the petal width
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [67]:
iris["prediction"] = model.predict(X)
iris["residual"] = iris["prediction"] - iris["petal_width"]

In [68]:
fig = px.scatter(
    data_frame=iris,
    x="prediction",
    y="residual",
    marginal_y="violin",
    color="split",
    trendline="ols",
)
fig.show()

## Visualize regularization across cross-validation folds

In this example, we show how to plot the results of various $\alpha$ penalization values from the results of cross-validation using scikit-learn's LassoCV. This is useful to see how much the error of the optimal alpha actually varies across CV folds.

In [82]:
from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler

In [70]:
N_FOLD = 6

In [74]:
gapminder = px.data.gapminder()
gapminder.head()

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4

In [76]:
X = gapminder.drop(columns=["lifeExp", "iso_num"])
X = pd.get_dummies(X, columns=["country", "continent", "iso_alpha"])
y = gapminder["lifeExp"]

In [83]:
ss = StandardScaler()
X = ss.fit_transform(X)

In [84]:
model = LassoCV(
    cv=N_FOLD,
)
model.fit(X, y)

LassoCV(cv=6)

In [85]:
mean_alphas = model.mse_path_.mean(axis=-1)
mean_alphas

array([167.71597364, 160.80453736, 152.35440325, 143.60859769,
       135.45015896, 128.42843392, 121.80778673, 114.61371921,
       107.77828794, 100.99132083,  94.86716352,  89.54989892,
        84.933884  ,  80.92722921,  77.45001326,  74.43271429,
        71.81497933,  69.54432278,  67.57770582,  65.83883539,
        64.31810427,  62.99729463,  61.85042098,  60.85808705,
        60.04717102,  59.32948897,  58.74932251,  58.25674297,
        57.81803447,  57.43751058,  57.06698636,  56.70498316,
        56.35678156,  55.99173641,  55.65070798,  55.33630473,
        54.98525187,  54.71417748,  54.55529971,  54.44963046,
        54.34306384,  54.26864904,  54.24502948,  54.21740267,
        54.18309403,  54.18993959,  54.18014445,  54.15773578,
        54.12231204,  54.11012868,  54.0927162 ,  54.07553152,
        54.0731339 ,  54.09793793,  54.135563  ,  54.18104837,
        54.23684652,  54.32005416,  54.40964372,  54.54969978,
        54.76248856,  55.01882789,  55.28847368,  55.56

In [86]:
fig = go.Figure(
    data=[
        go.Scatter(
            x=model.alphas_,
            y=model.mse_path_[:, i],
            name=f"Fold: {i+1}",
            opacity=0.5,
            line=dict(dash="dash"),
            hovertemplate="alpha: %{x} <br>MSE: %{y}",
        )
        for i in range(N_FOLD)
    ]
)
fig.add_traces(
    go.Scatter(
        x=model.alphas_,
        y=mean_alphas,
        name="Mean",
        line=dict(color="black", width=3),
        hovertemplate="alpha: %{x} <br>MSE: %{y}",
    )
)

fig.add_shape(
    type="line",
    line=dict(dash="dash"),
    x0=model.alpha_,
    y0=0,
    x1=model.alpha_,
    y1=1,
    yref="paper",
)

fig.update_layout(
    xaxis_title="alpha", xaxis_type="log", yaxis_title="Mean Square Error (MSE)"
)
fig.show()

## Grid search visualization using px.density_heatmap and px.box

In this example, we show how to visualize the results of a grid search on a DecisionTreeRegressor. The first plot shows how to visualize the score of each model parameter on individual splits (grouped using facets). The second plot aggregates the results of all splits such that each box represents a single model.

In [87]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

In [88]:
N_FOLD = 6

In [89]:
iris = px.data.iris()
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [90]:
# shuffle dataframe
iris = iris.sample(frac=1, random_state=0)
iris.head()

sepal_length  sepal_width  petal_length  petal_width     species  \
114           5.8          2.8           5.1          2.4   virginica   
62            6.0          2.2           4.0          1.0  versicolor   
33            5.5          4.2           1.4          0.2      setosa   
107           7.3          2.9           6.3          1.8   virginica   
7             5.0          3.4           1.5          0.2      setosa   

     species_id  
114           3  
62            2  
33            1  
107           3  
7             1

In [91]:
X = iris[["sepal_width", "sepal_length"]]
y = iris["petal_width"]

In [92]:
model = DecisionTreeRegressor()
model

DecisionTreeRegressor()

In [99]:
# Define and fit the grid
param_grid = {"criterion": ["mse", "friedman_mse", "mae"], "max_depth": range(2, 5)}

In [100]:
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=N_FOLD)
grid.fit(X, y)

d:\miniconda3\envs\pytorch\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:


36 fits failed out of a total of 54.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
18 fits failed with the following error:
Traceback (most recent call last):
  File "d:\miniconda3\envs\pytorch\Lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\miniconda3\envs\pytorch\Lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "d:\miniconda3\envs\pytorch\Lib\site-packages\sklearn\base.py", line 638, in _validate_params
    validate_parameter_constraints(
  File "d:\miniconda3\envs\pytorch\Lib\sit

GridSearchCV(cv=6, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['mse', 'friedman_mse', 'mae'],
                         'max_depth': range(2, 5)})

In [101]:
grid_df = pd.DataFrame(grid.cv_results_)
grid_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000667      0.000472         0.000000        0.000000   
1       0.000667      0.000471         0.000000        0.000000   
2       0.000333      0.000471         0.000000        0.000000   
3       0.001168      0.000373         0.000999        0.000001   
4       0.001500      0.000500         0.001000        0.000577   
5       0.001166      0.000373         0.000834        0.000373   
6       0.000167      0.000372         0.000000        0.000000   
7       0.000333      0.000471         0.000000        0.000000   
8       0.000334      0.000472         0.000000        0.000000   

  param_criterion param_max_depth  \
0             mse               2   
1             mse               3   
2             mse               4   
3    friedman_mse               2   
4    friedman_mse               3   
5    friedman_mse               4   
6             mae               2   
7             mae               3   
8             mae               4   

                                          params  split0_test_score  \
0           {'criterion': 'mse', 'max_depth': 2}                NaN   
1           {'criterion': 'mse', 'max_depth': 3}                NaN   
2           {'criterion': 'mse', 'max_depth': 4}                NaN   
3  {'criterion': 'friedman_mse', 'max_depth': 2}           0.555726   
4  {'criterion': 'friedman_mse', 'max_depth': 3}           0.642535   
5  {'criterion': 'friedman_mse', 'max_depth': 4}           0.686885   
6           {'criterion': 'mae', 'max_depth': 2}                NaN   
7           {'criterion': 'mae', 'max_depth': 3}                NaN   
8           {'criterion': 'mae', 'max_depth': 4}                NaN   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                NaN                NaN                NaN                NaN   
1                NaN                NaN                NaN                NaN   
2                NaN                NaN                NaN                NaN   
3           0.660036           0.689600           0.828371           0.801878   
4           0.766531           0.704990           0.865185           0.876963   
5           0.744497           0.715511           0.847842           0.850529   
6                NaN                NaN                NaN                NaN   
7                NaN                NaN                NaN                NaN   
8                NaN                NaN                NaN                NaN   

   split5_test_score  mean_test_score  std_test_score  rank_test_score  
0                NaN              NaN             NaN                4  
1                NaN              NaN             NaN                4  
2                NaN              NaN             NaN                4  
3           0.816293         0.725317        0.099211                3  
4           0.824245         0.780075        0.084971                1  
5           0.834067         0.779889        0.066570                2  
6                NaN              NaN             NaN                4  
7                NaN              NaN             NaN                4  
8                NaN              NaN             NaN                4

In [104]:
# Convert the wide format of the grid into the long format
# accepted by plotly.express
melted = grid_df.rename(columns=lambda col: col.replace("param_", "")).melt(
    value_vars=[f"split{i}_test_score" for i in range(N_FOLD)],
    id_vars=["mean_test_score", "mean_fit_time", "criterion", "max_depth"],
    var_name="cv_split",
    value_name="r_squared",
)
melted.head()

mean_test_score  mean_fit_time     criterion max_depth           cv_split  \
0              NaN       0.000667           mse         2  split0_test_score   
1              NaN       0.000667           mse         3  split0_test_score   
2              NaN       0.000333           mse         4  split0_test_score   
3         0.725317       0.001168  friedman_mse         2  split0_test_score   
4         0.780075       0.001500  friedman_mse         3  split0_test_score   

   r_squared  
0        NaN  
1        NaN  
2        NaN  
3   0.555726  
4   0.642535

In [106]:
melted["cv_split"] = (
    melted["cv_split"].str.replace("_test_score", "").str.replace("split", "")
)

In [108]:
fig_hmap = px.density_heatmap(
    data_frame=melted,
    x="max_depth",
    y="criterion",
    histfunc="sum",
    z="r_squared",
    title="Grid search results on individual fold",
    hover_data=["mean_fit_time"],
    facet_col="cv_split",
    facet_col_wrap=3,
    labels={"mean_test_score": "mean_r_squared"},
)

fig_box = px.box(
    data_frame=melted,
    x="max_depth",
    y="r_squared",
    title="Grid search results ",
    hover_data=["mean_fit_time"],
    points="all",
    color="criterion",
    hover_name="cv_split",
    labels={"mean_test_score": "mean_r_squared"},
)

fig_hmap.show()
fig_box.show()